---

internal_root_domain: "dettonville.int"
ca_domain: "{{ internal_root_domain }}"

#ca_commonName: "ca.dettonville.int"
#ca_domainName: "dettonville.int"
#ca_signerName: "{{ ca_root_cn }}"
ca_country: US
ca_state: "New York"
ca_locality: "NYC"
ca_organization: "Dettonville Internal"
ca_organizationalUnit: "Research & Technology"
ca_email: "admin@{{ ca_domain }}"

dns_search_domains:
  - dettonville.int

ldap_internal_domain: "dettonville.int"
ldap_internal_base_dn: "dc=dettonville,dc=int"
