---

__docker_stack__proxyspec__awx:
  http:
    routers:
      awx-rtr:
        rule: "Host(`awx.{{ docker_stack__internal_domain }}`)"
        entryPoints:
          - https
          ## ref: https://stackoverflow.com/questions/46313356/how-to-proxy-websockets-in-traefik
          - ws
          - wss
        service: awx-svc
    services:
      awx-svc:
        loadBalancer:
          servers:
            - url: "{{ __docker_stack__proxyspec__awx_backend }}"

docker_stack__proxyspec__awx:
  proxy_config: "{{ __docker_stack__proxyspec__awx | d({}) }}"
