# Copyright 2017 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: MIT OR GPL-3.0-only
---
- name: Download an alternative version
  hosts: all
  roles:
    - { role: ansible-role-govc, govc_version: "0.19.0" }
