---

## ntp-client configs
## ref: https://github.com/geerlingguy/ansible-role-ntp
ntp_timezone: America/New_York

ntp_tinker_panic: yes

ntp_servers_yaml: |
  [
    {% if groups['ntp_server'] is defined %}
    {% for server in groups['ntp_server'] %}
    {% for network in hostvars[server]['ntp_allow_networks']|d([]) %}
    {% if network|ansible.netcommon.network_in_usable(ansible_default_ipv4.address) %}
    "{{ server }}",
    {% endif %}
    {% endfor %}
    {% endfor %}
    {% endif %}
  ]

ntp_servers: "{{ ntp_servers_yaml | from_yaml }}"

##
## the following can mistakenly add ntp servers that exclude the client
##
# ntp_servers_yaml: |
#  [
#    {% if groups['ntp_server'] is defined %}
#    {% for server in groups['ntp_server'] %}
#    "{{ server }}",
#    {% endfor %}
#    {% endif %}
#  ]
# ntp_servers: "{{ ntp_servers_yaml | from_yaml }}"

ntp_cmdport_disabled: yes

## used for variable-to-inventory trace/debug
group_trace_var: group_vars/ntp_client_internal.yml
