## ref: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#installing-collections-with-ansible-galaxy

roles:
  ## Install a role from the Ansible Galaxy
  # how to install ansible requirements
  # ref: https://stackoverflow.com/questions/25230376/how-to-automatically-install-ansible-galaxy-roles
  # ref: https://zaiste.net/automatically_install_ansible_galaxy_roles_with_requirements_yml/

  - name: geerlingguy.git
    version: master
  - name: geerlingguy.java
    version: master
  - name: geerlingguy.pip
    version: master
  - name: geerlingguy.ansible
    version: master
  - name: geerlingguy.awx
    version: master
  - name: geerlingguy.nfs
    version: master
  - name: geerlingguy.jenkins
    version: master
  - name: geerlingguy.repo-epel
    version: master
  - name: geerlingguy.nodejs
    version: master
  - name: geerlingguy.postfix
    version: master
  - name: geerlingguy.packer
    version: master
  - name: gantsign.maven
    version: master
#  - name: tecris.maven
#    version: master
  - name: bertvv.dhcp
    version: master
  - name: avinetworks.docker
    version: master
  - name: githubixx.cfssl
    version: master
  - name: mrlesmithjr.netplan
    version: master
  - name: mrlesmithjr.cloud-init
    version: master
  - name: mrlesmithjr.ansible-config-interfaces
    src: https://github.com/mrlesmithjr/ansible-config-interfaces.git
    version: master
  - name: mrlesmithjr.ansible-kvm
    src: https://github.com/mrlesmithjr/ansible-kvm.git
    version: master
  - name: willshersystems.sshd
    version: master
  - name: grog.package
    version: master
  - name: rossmcdonald.telegraf
    version: master
  - name: tumf.systemd-service
    version: master
#  - name: ironicbadger.ansible_role_snapraid
#    version: master
#  - name: sbaerlocher.veeam-agent
#    version: master

# collections:

#   - name: ansible.posix

#   - name: community.general

#   ## ref: https://github.com/ansible-collections/community.general/blob/stable-2/CHANGELOG.rst#id8
#   - name: community.docker

# #  ## ref: https://galaxy.ansible.com/community/vmware
# #  - name: community.vmware

#   - name: dellemc.openmanage
#     src: git+https://github.com/dell/dellemc-openmanage-ansible-modules.git,collections
# #    source: https://github.com/dell/dellemc-openmanage-ansible-modules.git

#   - name: sivel.toiletwater
#     src: https://github.com/sivel/toiletwater.git,collections
# #    source: https://github.com/sivel/toiletwater.git
# #    version: collections

#   - name: lvrfrc87.git_acp
#     src: git+https://github.com/lvrfrc87/git-acp-ansible.git
# #    source: git+https://github.com/lvrfrc87/git-acp-ansible.git
# #    version: master
