## ref: https://docs.ansible.com/ansible/latest/user_guide/collections_using.html#installing-collections-with-ansible-galaxy

roles:
  ## Install a role from the Ansible Galaxy
  # how to install ansible requirements
  # ref: https://stackoverflow.com/questions/25230376/how-to-automatically-install-ansible-galaxy-roles
  # ref: https://zaiste.net/automatically_install_ansible_galaxy_roles_with_requirements_yml/

  - name: geerlingguy.ansible
    src: https://github.com/geerlingguy/ansible-role-ansible
    version: master

  - name: geerlingguy.git
    src: https://github.com/geerlingguy/ansible-role-git.git
    version: master

  - name: geerlingguy.jenkins
    src: https://github.com/geerlingguy/ansible-role-jenkins
    version: master
  #  version: "3.8.0"

  - name: geerlingguy.repo-epel
    src: https://github.com/geerlingguy/ansible-role-repo-epel
    version: master

  - name: gantsign.maven
    src: https://github.com/gantsign/ansible-role-maven
    version: master

#  - name: geerlingguy.nodejs
#    src: https://github.com/geerlingguy/ansible-role-nodejs
#    version: master

#  - name: geerlingguy.nfs
#    src: https://github.com/geerlingguy/ansible-role-nfs
#    version: master

#  - name: geerlingguy.pip
#    src: https://github.com/geerlingguy/ansible-role-pip
#    version: master

#  - name: geerlingguy.java
#    src: https://github.com/geerlingguy/ansible-role-java
#    version: master
#  #  version: "1.9.7"

#  - name: geerlingguy.ntp
#    src: https://github.com/geerlingguy/ansible-role-ntp
#    version: master

#  - name: geerlingguy.postfix
#    src: https://github.com/geerlingguy/ansible-role-postfix
#    version: master

#  - name: geerlingguy.packer
#    src: https://github.com/geerlingguy/ansible-role-packer
#    version: master

#  - name: geerlingguy.awx
#    src: https://github.com/geerlingguy/ansible-role-awx
#    version: master

#  - name: tecris.maven
#    src: https://github.com/tecris/ansible-maven
#    version: master

#  - name: bertvv.dhcp
#    src: https://github.com/bertvv/ansible-role-dhcp
#    version: master

#  - name: avinetworks.docker
#    src: https://github.com/avinetworks/ansible-role-docker
#    version: master

#  - name: githubixx.cfssl
#    src: https://github.com/githubixx/ansible-role-cfssl
#    version: master

#  - name: mrlesmithjr.netplan
#    src: https://github.com/mrlesmithjr/ansible-netplan
#    version: master

#  - name: mrlesmithjr.cloud-init
#    src: https://github.com/mrlesmithjr/ansible-cloud-init
#    version: master

#  - name: mrlesmithjr.ansible-config-interfaces
#    src: https://github.com/mrlesmithjr/ansible-config-interfaces.git
#    version: master

#  - name: willshersystems.sshd
#    src: https://github.com/willshersystems/ansible-sshd
#    version: master

#  - name: grog.package
#    src: https://github.com/GROG/ansible-role-package.git
#    version: master

#  - name: rossmcdonald.telegraf
#    src: https://github.com/rossmcdonald/telegraf.git
#    version: master

#  - name: tumf.systemd-service
#    src: https://github.com/tumf/ansible-role-systemd-service
#    version: master

#  - name: ironicbadger.ansible_role_snapraid
#    src: https://github.com/IronicBadger/ansible-role-snapraid.git
#    version: master

  #- name: sbaerlocher.veeam-agent
  #  src: https://github.com/sbaerlocher/ansible.veeam-agent
  #  version: master

collections:

  - name: ansible.posix

  - name: ansible.windows

  - name: ansible.netcommon

  - name: community.general

  ## ref: https://galaxy.ansible.com/community/vmware
  - name: community.vmware

  ## ref: https://github.com/ansible-collections/community.general/blob/stable-2/CHANGELOG.rst#id8
  - name: community.docker

  ## ref: https://docs.ansible.com/ansible/latest/collections/awx/awx/index.html#plugins-in-awx-awx
  ## ref: https://www.ansible.com/blog/introducing-the-awx-collection
  - name: awx.awx
    version: 19.4.0
#    version: 17.1.0

  - name: openstack.cloud

  - name: dellemc.openmanage
    src: git+https://github.com/dell/dellemc-openmanage-ansible-modules.git,collections
  #  src: https://github.com/dell/dellemc-openmanage-ansible-modules/tree/collections
  #  version: master

  - name: sivel.toiletwater
    src: https://github.com/sivel/toiletwater.git,collections
  #  version: master

  - name: lvrfrc87.git_acp
    src: https://github.com/lj020326/git-acp-ansible.git,master
#    src: git+https://github.com/lvrfrc87/git-acp-ansible.git,master

#  - steampunk.aws
