---
# defaults file for rbicker.cobbler

# password=root -> set to a value given by openssl passwd -1
cobbler_default_password_crypted: $1$asdf3421$dEw9zCFxyo9KG3Y2xsd/n0
# password=cobbler -> set value using htdigest
cobbler_web_password_crypted: a2d6bae81669d707b72c0bd9806e01f3
cobbler_pxe_just_once: yes
cobbler_manage_dhcp: no
cobbler_manage_dns: no
cobbler_isos_path: /etc/cobbler/distro-isos
cobbler_isos_mount_path: /mnt/cobbler
cobbler_isos_delete: true
cobbler_profiles:
  - name: centos7
    arch: x86_64
    url: http://mirror.switch.ch/ftp/mirror/centos/7/isos/x86_64/CentOS-7-x86_64-DVD-1611.iso
cobbler_kickstart_path: /var/lib/cobbler/kickstarts
cobbler_templates_force: true

### added
cobbler_firewalld_services: []
#  - name: ldap

#cobbler_firewalld_ports:
#  - 389/tcp
#  - 69/udp
#  - 80/tcp
#  - 443/tcp
#  - 25151/tcp

bind_packages:
  Debian:
    - bind9
    - bind9utils
  RedHat:
    - bind
    - bind-utils
    - bind-chroot

dhcp_packages:
  Debian:
    - isc-dhcp-server
  RedHat:
    - dhcp-common

cobbler_depends_packages:
  ## ref: https://github.com/ArdanaCLM/cobbler-ansible/blob/master/roles/cobbler/vars/debian.yml
  Debian:
    - python-jsonschema
    - python-yaml
    - cobbler
    - syslinux-common
    - debian-installer-8-netboot-amd64
    - tftpd-hpa
    - xinetd
    - fence-agents
    - ipmitool
    - shim-signed
    - grub-efi-amd64-signed
  RedHat:
    ## ref: https://cobbler.readthedocs.io/en/latest/installation-guide.html#rpm
    - createrepo
    - httpd
    - mod_wsgi
    - mod_ssl
    - python-cheetah
    - python-netaddr
    - python-simplejson
    - python-urlgrabber
    - PyYAML
    - rsync
    - syslinux
    - tftp-server
    - yum-utils
    - python-django
    - debmirror
    - pykickstart
    - fence-agents-all
    - nano
    - xinetd

cobbler_packages:
  Debian:
    - cobbler
  RedHat:
    - cobbler
    - cobbler-web

cobbler_build_packages:
  ## ref: https://cobbler.readthedocs.io/en/latest/installation-guide.html#deb
  Debian:
    - make
    - openssl
    - python-devel
    - python-cheetah
    - python-yaml
    - python-cheetah
    - python-netaddr
    - python-simplejson
    - python-urlgrabber
    - libapache2-mod-wsgi
    - python-django
    - atftpd
  ## ref: https://cobbler.readthedocs.io/en/latest/installation-guide.html#rpm
  RedHat:
    - make
    - openssl
    - httpd-devel
    - mod_wsgi
    - python-devel
    - python-cheetah

