---

#- name: restart iscsid
#  service:
#    name: "{{ iscsid_service }}"
#    state: restarted
#    sleep: 5

- name: "restart iscsi service"
  service:
    name: "{{ iscsid_service }}"
    state: restarted
