---

docker_stack_appspec_services__jenkins_agent:

  ## JENKINS INBOUNT AGENT #1
  ## ref: https://github.com/jenkinsci/docker-inbound-agent
  ## ref: https://github.com/cloudbees/jnlp-slave-with-java-build-tools-dockerfile
  ## ref: https://wiki.tds.tieto.com/display/TDSKB/Executing+Jenkins+jobs+when+only+one+way+network+connection+exists
  ## ref: https://stackoverflow.com/questions/58719522/tcpslaveagentlistener-is-invalid-404-not-found
  jenkins-agent:
    container_name: jenkins-agent
    image: "{{ __docker_stack_appspecs__jenkins_agent_image }}"
    environment:
      TZ: "{{ docker_stack_timezone }}"
      JENKINS_URL: "{{ __docker_stack_appspecs__jenkins_agent_jenkins_url }}"
      JENKINS_TUNNEL: "{{ __docker_stack_appspecs__jenkins_agent_tunnel }}"
      JENKINS_AGENT_WORKDIR: "{{ __docker_stack_appspecs__jenkins_agent_workdir }}"
      JENKINS_SECRET: "{{ __docker_stack_appspecs__jenkins_agent_secret }}"
      JENKINS_AGENT_NAME: "{{ __docker_stack_appspecs__jenkins_agent_name }}"
      JAVA_OPTS: "-Djavax.net.ssl.trustStore=/var/lib/jenkins/cacerts -Djavax.net.ssl.trustStorePassword=changeit"
#      DOCKER_HOST: tcp://socket-proxy:2375
      gid: "{{ docker_stack_user_gid }}"
      uid: "{{ docker_stack_user_uid }}"
    networks:
      - "{{ docker_stack_traefik_proxy_network }}"
      - socket_proxy
    ports:
      - "{{ __docker_stack_appspecs__jenkins_agent_ssh_port }}:4444/tcp"
    restart: unless-stopped
#    depends_on:
#      - jenkins
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "{{ __docker_stack_appspecs__jenkins_agent_base_dir }}/passwd:/etc/passwd:ro"
      - "{{ __docker_stack_appspecs__jenkins_agent_base_dir }}/group:/etc/group:ro"
      - "{{ __docker_stack_appspecs__jenkins_agent_base_dir }}/jenkins_home:/home/jenkins"
#      - "{{ __docker_stack_appspecs__jenkins_agent_base_dir }}/jenkins_home:/var/jenkins_home"
      - "{{ docker_stack_ca_cert_bundle }}:/etc/ssl/certs/ca-certificates.crt:ro"
      - "{{ docker_stack_ca_java_keystore }}:/var/lib/jenkins/cacerts"
#        - /etc/pki/ca-trust/extracted/java/cacerts:/home/jenkins/.cacerts
#        - /export/data/jenkins/osimages:/data
      - "{{ __docker_stack_appspecs__jenkins_agent_data_dir }}:/data"
      - "{{ __docker_stack_vmware_data_dir }}:/vmware"


