---
#__docker_stack_appspecs__base_traefik_image: traefik:v2.3
#__docker_stack_appspecs__base_traefik_image: traefik:picodon # the picodon tag refers to v2.3.x
#__docker_stack_appspecs__base_traefik_image: traefik:latest
__docker_stack_appspecs__base_traefik_image: traefik:v2.9.6

__docker_stack_appspecs__base_traefik_auth_labels:
    ## Middlewares
    traefik.http.routers.traefik-rtr.middlewares: chain-oauth@file

__docker_stack_appspecs__base_traefik_labels_default:
  #autoheal: true
  traefik.enable: true
  # HTTP-to-HTTPS Redirect
  traefik.http.routers.http-catchall.entrypoints: http
  traefik.http.routers.http-catchall.rule: HostRegexp(`{host:.+}`)
  traefik.http.routers.http-catchall.middlewares: redirect-to-https
  traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
  ## Services - API
  traefik.http.routers.traefik-rtr.service: api@internal
  traefik.http.routers.traefik-rtr.entrypoints: https
##  traefik.http.routers.traefik-rtr.rule: Host(`{{ docker_stack_internal_domain }}`) && (PathPrefix(`/api`) || PathPrefix(`/traefik`))
#  traefik.http.routers.traefik-rtr.rule: PathPrefix(`/api`) || PathPrefix(`/dashboard`)
#  traefik.http.routers.traefik-rtr.middlewares: apistripprefix@docker
#  traefik.http.middlewares.apistripprefix.stripprefix.prefixes: /traefik
#  ## Auth Middleware
#  traefik.http.routers.api.middlewares: chain-oauth@file
  ## Healthcheck/ping
  traefik.http.routers.ping.entrypoints: https
  traefik.http.routers.ping.rule: Host(`{{ docker_stack_internal_domain }}`) && PathPrefix(`/ping`)
  traefik.http.routers.ping.service: ping@internal

#__docker_stack_appspecs__base_traefik_labels: "{{ __docker_stack_appspecs__base_traefik_labels_default | combine(__docker_stack_appspecs__base_traefik_auth_labels if 'auth' in docker_stack_service_configs else {}) }}"
__docker_stack_appspecs__base_traefik_labels: "{{ docker_stack_traefik__traefik_labels | d(__docker_stack_appspecs__base_traefik_labels_default) }}"

docker_stack_appspec_config_tpls__base:
  - { src: "traefik/config-traefik-v2.yml.j2", dest: "{{ __docker_stack_appspecs__base_traefik_dir }}/traefik.yml", backup: yes }
#  - { src: "traefik/rules/serviceTransport.yml.j2", dest: "{{ __docker_stack_appspecs__base_traefik_dir }}/rules/serviceTransport.yml" }
  - { src: "traefik/rules/middlewares.yml.j2", dest: "{{ __docker_stack_appspecs__base_traefik_dir }}/rules/middlewares.yml"}
  - { src: "traefik/rules/middlewares-chains.yml.j2", dest: "{{ __docker_stack_appspecs__base_traefik_dir }}/rules/middlewares-chains.yml"}
  - { src: "traefik/rules/certs-traefik.yml.j2", dest: "{{ __docker_stack_appspecs__base_traefik_dir }}/rules/certs-traefik.yml"}
  - { src: "traefik/rules/tls-opts.yml.j2", dest: "{{ __docker_stack_appspecs__base_traefik_dir }}/rules/tls-opts.yml"}
  - { src: "traefik/rules/tls-opts-strict.yml.j2", dest: "{{ __docker_stack_appspecs__base_traefik_dir }}/rules/tls-opts-strict.yml"}
  - { src: "docker-gc-exclude.conf.j2", dest: "{{ __docker_stack_appspecs__base_stack_dir }}/docker-gc/docker-gc-exclude" }
  - { src: 'compose.env.j2', dest: "{{ __docker_stack_appspecs__base_stack_dir }}/.env" }
  - { src: 'docker-compose.yml.j2', dest: "{{ __docker_stack_appspecs__base_stack_dir }}/docker-compose.yml", backup: yes }

## ref: https://github.com/htpcBeginner/docker-traefik/blob/master/docker-compose-t2.yml
docker_stack_appspec_services__base:
  ######### FRONTENDS ##########
  # Traefik Reverse Proxy
  traefik:
    container_name: traefik
    image: "{{ __docker_stack_appspecs__base_traefik_image }}"
    restart: unless-stopped
    networks:
#      - default
      - "{{ docker_stack_traefik_proxy_network }}"
      - socket_proxy
#    depends_on:
#      - socket-proxy
#    security_opt:
#      - no-new-privileges:true
    #healthcheck:
    #  test: ["CMD", "traefik", "healthcheck", "--ping"]
    #  interval: 5s
    #  retries: 3
    ports:
      - target: 80
        published: "{{ __docker_stack_appspecs__base_traefik_http }}"
        protocol: tcp
        mode: host
      - target: 443
        published: "{{ __docker_stack_appspecs__base_traefik_https }}"
        protocol: tcp
        mode: host
    environment:
      PUID: "{{ docker_user_uid }}"
      PGID: "{{ docker_user_gid }}"
      TZ: "{{ docker_stack_timezone }}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ __docker_stack_appspecs__base_traefik_dir }}:/etc/traefik"
      - "{{ __docker_stack_appspecs__base_traefik_dir }}/certs:/certs"
      - "{{ __docker_stack_appspecs__base_stack_dir }}/shared:/shared"
    labels: "{{ __docker_stack_appspecs__base_traefik_labels }}"

  # Docker Socket Proxy - Security Enchanced Proxy for Docker Socket
  socket-proxy:
    container_name: socket-proxy
    image: fluencelabs/docker-socket-proxy
    restart: always
    networks:
      - socket_proxy
#      - "{{ docker_stack_traefik_proxy_network }}"
    privileged: true
    ports:
      - "127.0.0.1:2375:2375" # Port 2375 should only ever get exposed to the internal network.
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      LOG_LEVEL: debug # debug,info,notice,warning,err,crit,alert,emerg
      ## Variables match the URL prefix (i.e. AUTH blocks access to /auth/* parts of the API, etc.).
      # 0 to revoke access.
      # 1 to grant access.
      ## Granted by Default
      EVENTS: 1
      PING: 1
      VERSION: 1
      ## Revoked by Default
      # Security critical
      AUTH: 0
      SECRETS: 0
      POST: 1 # Watchtower
      DELETE: 1 # Watchtower
        # GET Optons
      BUILD: 0
      COMMIT: 0
      CONFIGS: 0
      CONTAINERS: 1 # Traefik, portainer, etc.
      DISTRIBUTION: 0
      EXEC: 0
      IMAGES: 1 # Portainer, Watchtower
      INFO: 1 # Portainer
      NETWORKS: 1 # Portainer, Watchtower
      NODES: 0
      PLUGINS: 0
      SERVICES: 1 # Portainer
      SESSION: 0
      SWARM: 0
      SYSTEM: 0
      TASKS: 1 # Portainer
      VOLUMES: 1 # Portainer
      # POST Options
      CONTAINERS_CREATE: 1 # WatchTower
      CONTAINERS_START: 1 # WatchTower
      CONTAINERS_UPDATE: 1 # WatchTower
      # DELETE Options
      CONTAINERS_DELETE: 1 # WatchTower
      IMAGES_DELETE: 1 # WatchTower

  ## Whoami - useful for debugging traefik config related issues
  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    hostname: "whoami"
    networks:
      - "{{ docker_stack_traefik_proxy_network }}"
    labels:
      traefik.enable: true
      ## HTTP Routers
      traefik.http.routers.whoami-rtr-int.entrypoints: https
      traefik.http.routers.whoami-rtr-int.rule: Host(`{{ docker_stack_internal_domain }}`) && Path(`/whoami`)

  ######### DOCKER RELATED ##########
  # Watchtower - Automatic Update of Containers/Apps
  watchtower:
#    image: v2tec/watchtower
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    networks:
      - default
      - socket_proxy
    depends_on:
      - socket-proxy
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "{{ docker_stack_timezone }}"
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_REMOVE_VOLUMES: "true"
      WATCHTOWER_INCLUDE_STOPPED: "true"
      WATCHTOWER_NO_STARTUP_MESSAGE: "false"
      WATCHTOWER_SCHEDULE: "0 30 12 * * *" # Everyday at 12:30
#      WATCHTOWER_NOTIFICATIONS: shoutrrr
      WATCHTOWER_NOTIFICATIONS_LEVEL: info
#      WATCHTOWER_NOTIFICATION_URL: "telegram://{{ __docker_stack_appspecs__base_tgram_bot_token }}@telegram?channels={{ __docker_stack_appspecs__base_tgram_chat_id }}"
      DOCKER_HOST: tcp://socket-proxy:2375
#      DOCKER_API_VERSION: "1.40"

  # Docker-GC - Automatic Docker Garbage Collection
  # Create docker-gc-exclude file
  dockergc:
    image: clockworksoul/docker-gc-cron:latest
    container_name: docker-gc
    restart: unless-stopped
    networks:
      - socket_proxy
    depends_on:
      - socket-proxy
    volumes:
      # - /var/run/docker.sock:/var/run/docker.sock # Use Docker Socket Proxy instead for improved security
      ## https://github.com/clockworksoul/docker-gc-cron
      - "{{ __docker_stack_appspecs__base_stack_dir }}/docker-gc/docker-gc-exclude:/etc/docker-gc-exclude"
    environment:
      CRON: 0 0 0 * * ? # Everyday at midnight. Previously 0 0 * * *
      FORCE_IMAGE_REMOVAL: 1
      FORCE_CONTAINER_REMOVAL: 0
      GRACE_PERIOD_SECONDS: 604800
      DRY_RUN: 0
      CLEAN_UP_VOLUMES: 1
      TZ: "{{ docker_stack_timezone }}"
      DOCKER_HOST: tcp://socket-proxy:2375

  # Portainer - WebUI for Containers
  portainer:
    container_name: portainer
#    image: "portainer/portainer-ce:latest"
    image: "portainer/portainer-ce:2.17.0"
    restart: unless-stopped
    environment:
      TZ: "{{ docker_stack_timezone }}"
    networks:
      - "{{ docker_stack_traefik_proxy_network }}"
#      - socket_proxy
#    depends_on:
#      - socket-proxy
    ports:
     - target: 9000
       published: 9010
       protocol: tcp
       mode: host
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ __docker_stack_appspecs__base_stack_dir }}/portainer/data:/data"
    labels:
      traefik.enable: true
      ## HTTP Routers
      traefik.http.routers.portainer-rtr.entrypoints: https
      traefik.http.routers.portainer-rtr.rule: Host(`{{ docker_stack_internal_domain }}`) && PathPrefix(`/portainer`)

      ## ref: https://community.traefik.io/t/pathprefix-and-strip/2122/2
      traefik.http.middlewares.portainerpathstrip.stripprefix.prefixes: /portainer
      traefik.http.middlewares.portainerpathstrip.stripprefix.forceSlash: false
      traefik.http.routers.portainer-rtr.middlewares: portainerpathstrip@docker
      traefik.http.routers.portainer-rtr.service: portainer-svc
      traefik.http.services.portainer-svc.loadbalancer.server.port: 9000

  # Dozzle - Real-time Docker Log Viewer
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: unless-stopped
    networks:
      - "{{ docker_stack_traefik_proxy_network }}"
      - socket_proxy
    depends_on:
      - socket-proxy
    security_opt:
      - no-new-privileges:true
    environment:
      DOZZLE_LEVEL: info
      DOZZLE_TAILSIZE: 300
      DOZZLE_BASE: /dozzle
      DOZZLE_FILTER: "status=running"
      # DOZZLE_FILTER: "label=log_me" # limits logs displayed to containers with this label
      DOCKER_HOST: tcp://socket-proxy:2375
    ports:
     - target: 8080
       published: 8080
       protocol: tcp
       mode: host
    # volumes:
    #  - /var/run/docker.sock:/var/run/docker.sock # Use Docker Socket Proxy instead for improved security
    labels:
      traefik.enable: true
      ## HTTP Routers
      traefik.http.routers.dozzle-rtr.entrypoints: https
      traefik.http.routers.dozzle-rtr.rule: Host(`{{ docker_stack_internal_domain }}`) && PathPrefix(`/dozzle`)
      ## ref: https://community.traefik.io/t/pathprefix-and-strip/2122/2
      traefik.http.routers.dozzle-rtr.service: dozzle-svc
      traefik.http.services.dozzle-svc.loadbalancer.server.port: 8080
