---

vmware_node_disk_size_gb: 40
vmware_vm_memory_mb: 8192
#vmware_node_network_type: static

#ipv4_address: 192.168.20.15
#ipv4_address: "{{ gateway_ip4_subnet_1_2 }}.20.15"
#ipv4_net_prefix: 16

bind_aliases:
#  - "{{ docker_stack_service_route_name }}"
  - ns2
#  - mail
#  - ldap
#  - auth


