---

ipv4_address: "{{ gateway_ipv4_subnet_1_2 }}.0.20"

docker_stack_registry_enable_auth: false

# docker_stack__registry__data_path: "/srv/data2/data/docker_registry"
# docker_stack__registry__data_path: "/srv/data2/docker_registry"
# docker_stack__registry__data_path: "/export/data/docker_registry"
docker_stack__registry__data_path: "/data/docker_registry"

is_veeam_backup_server: true
