---

## ref: https://opensource.com/article/19/5/hardware-bootstrapping-ansible
## ref: https://github.com/phips/ansible-hw-bootstrap
## ref: https://github.com/phips/ansible-hw-bootstrap/blob/master/plays/reinstall.yml

- name: "generate default pxe file for each dist in {{ kickstart_tftpdir }}"
  ansible.builtin.template:
    src: "templates/{{ item.0.distro }}/{{ item.1 }}"
    dest: "{{ kickstart_tftpdir }}/{{ item.0.distro }}-{{ item.1 | basename | replace('.j2', '') }}"
    owner: "{{ netboot_uid | default(omit) }}"
    group: "{{ netboot_gid | default(omit) }}"
#  with_items: "{{ pxe_os_dist_list }}"
  loop: "{{ pxe_os_dist_list | subelements('ipxe_templates', { 'skip_missing': true }) }}"
  loop_control:
    label: "generate default pxe file for {{ item.0.distro }}"

#- name: Set PXE menu to install
#  file:
#    state: link
##    src: "{{ kickstart_tftpdir }}/{{ hostvars[item].distro | default(pxe_default_distro) }}-{{ hostvars[item].ipxe_installer | default(pxe_default_installer) }}"
#    src: "{{ hostvars[item].distro | default(pxe_default_distro) }}-{{ hostvars[item].ipxe_installer | default(pxe_default_installer) }}"
##    dest: "{{ kickstart_tftpdir }}/MAC-{{ hostvars[item]['ansible_default_ipv4']['macaddress'] | regex_replace(':','') }}.ipxe"
#    dest: "{{ kickstart_tftpdir }}/MAC-{{ hostvars[item]['mac_address'] | lower | regex_replace(':','') }}.ipxe"
#    owner: "{{ netboot_uid | default(omit) }}"
#    group: "{{ netboot_gid | default(omit) }}"
#  become: true
#  loop: "{{ groups['deploy_vm'] }}"
#  when:
#    - hostvars[item].mac_address is defined
##    - hostvars[item].distro is not defined


- name: Set PXE menu to install
  ansible.builtin.copy:
    remote_src: yes
#    src: "{{ kickstart_tftpdir }}/{{ hostvars[item].distro | default(pxe_default_distro) }}-{{ hostvars[item].ipxe_installer | default(pxe_default_installer) }}"
    src: "{{ kickstart_tftpdir }}/{{ hostvars[dhcp_hostname].distro | default(pxe_default_distro) }}-{{ hostvars[dhcp_hostname].ipxe_installer | default(pxe_default_installer) }}"
#    dest: "{{ kickstart_tftpdir }}/MAC-{{ hostvars[item]['ansible_default_ipv4']['macaddress'] | regex_replace(':','') }}.ipxe"
    dest: "{{ kickstart_tftpdir }}/MAC-{{ hostvars[dhcp_hostname]['mac_address'] | lower | regex_replace(':','') }}.ipxe"
    owner: "{{ netboot_uid | default(omit) }}"
    group: "{{ netboot_gid | default(omit) }}"
  become: true
  loop: "{{ groups['deploy_vm'] }}"
  loop_control:
    loop_var: dhcp_hostname
  when:
    - hostvars[dhcp_hostname].mac_address is defined
#    - hostvars[item].distro is not defined
