---

- ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version}}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

## ref: https://smallstep.com/docs/step-ca/installation
- name: Setup step cli
  ansible.builtin.include_tasks: setup-stepca-cli.yml

### ref: https://smallstep.com/docs/step-ca/getting-started#initialize-your-certificate-authority
#- name: Bootstrap step cli configuration with remote ca server
#  ansible.builtin.include_tasks: bootstrap-stepca-cli.yml

- name: Setup step ca server
  when: stepca_ca_server
  ansible.builtin.include_tasks: setup-stepca-server.yml

