---

- name: "{{ __deploy_cacerts__log_prefix_fetch }} Fetch __deploy_cacerts__stepca_root_ca_fingerprint"
  when: not deploy_cacerts__stepca_root_ca_fingerprint is defined
#      run_once: true
  block:

    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Display deploy_cacerts__stepca_host_url"
      ansible.builtin.debug:
        var: deploy_cacerts__stepca_host_url

    ## ref: https://smallstep.com/blog/embarrassingly-easy-certificates-on-aws-azure-gcp/
    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Set __deploy_cacerts__stepca_root_ca_fingerprint_result"
#          run_once: true
#          ansible.builtin.shell: |
#            curl -k -s {{ deploy_cacerts__stepca_host_url }}/1.0/roots | jq -r '.crts[0]' | sed -r '/^\s*$/d'
      ansible.builtin.uri:
        url: "{{ deploy_cacerts__stepca_host_url }}1.0/roots"
#            method: GET
        validate_certs: false
        return_content: true
        body_format: json
        follow_redirects: none
        status_code:
          - 200
          - 201
      register: __deploy_cacerts__stepca_root_ca_fingerprint_result

    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Display __deploy_cacerts__stepca_root_ca_fingerprint_result"
      ansible.builtin.debug:
        var: __deploy_cacerts__stepca_root_ca_fingerprint_result

    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Set __deploy_cacerts__stepca_root_ca_fingerprint_encoded"
      ansible.builtin.set_fact:
        __deploy_cacerts__stepca_root_ca_fingerprint_encoded: "{{
          __deploy_cacerts__stepca_root_ca_fingerprint_result['json']['crts'][0] | trim }}"

    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Display __deploy_cacerts__stepca_root_ca_fingerprint_encoded"
      ansible.builtin.debug:
        var: __deploy_cacerts__stepca_root_ca_fingerprint_encoded

    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Ensure /tmp/stepca_root_ca_fingerprint_encoded.txt"
      ansible.builtin.copy:
        dest: /tmp/stepca_root_ca_fingerprint_encoded.txt
        content: "{{ __deploy_cacerts__stepca_root_ca_fingerprint_encoded }}"
        mode: "0600"

    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Get __deploy_cacerts__stepca_root_ca_fingerprint_decoded"
      changed_when: false
      ansible.builtin.shell: |
        step certificate fingerprint /tmp/stepca_root_ca_fingerprint_encoded.txt
#            step certificate fingerprint <\(echo {{ __deploy_cacerts__stepca_root_ca_fingerprint_encoded | quote }}\)
#            step certificate fingerprint <(echo {{ __deploy_cacerts__stepca_root_ca_fingerprint_encoded | quote }})
#              <(curl -k -s https://stepca.example.int/1.0/roots | jq -r '.crts[0]' | sed -r '/^\s*$/d')
      register: __deploy_cacerts__stepca_root_ca_fingerprint_decoded

    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Display __deploy_cacerts__stepca_root_ca_fingerprint_decoded"
      ansible.builtin.debug:
        var: __deploy_cacerts__stepca_root_ca_fingerprint_decoded

    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Set __deploy_cacerts__stepca_root_ca_fingerprint"
      ansible.builtin.set_fact:
        __deploy_cacerts__stepca_root_ca_fingerprint: "{{ __deploy_cacerts__stepca_root_ca_fingerprint_decoded.stdout }}"

- name: "{{ __deploy_cacerts__log_prefix_fetch }} Validate __deploy_cacerts__stepca_root_ca_fingerprint defined"
  ansible.builtin.assert:
    that: __deploy_cacerts__stepca_root_ca_fingerprint is defined

- name: "{{ __deploy_cacerts__log_prefix_fetch }} Check if {{ deploy_cacerts__cacert_local_cert_dir }}/{{ deploy_cacerts__pki_ca_root_cert }} exists"
  ansible.builtin.stat:
    path: "{{ deploy_cacerts__cacert_local_cert_dir }}/{{ deploy_cacerts__pki_ca_root_cert }}"
  register: __cacert_root_result

- name: "{{ __deploy_cacerts__log_prefix_fetch }} check host cert info"
  when: deploy_cacerts__validate_certs|d(true)|bool
  block:
    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Check if {{ deploy_cacerts__cacert_local_cert_dir }}/{{ deploy_cacerts__hostname_full }}.pem exists"
      ansible.builtin.stat:
        path: "{{ deploy_cacerts__cacert_local_cert_dir }}/{{ deploy_cacerts__hostname_full }}.pem"
      register: cacert_cert_result

    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Check if {{ deploy_cacerts__cacert_local_cert_dir }}/{{ deploy_cacerts__hostname_full }}.chain.pem exists"
      ansible.builtin.stat:
        path: "{{ deploy_cacerts__cacert_local_cert_dir }}/{{ deploy_cacerts__hostname_full }}.chain.pem"
      register: cacert_certbundle_result

    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Check if {{ deploy_cacerts__cacert_local_key_dir }}/{{ deploy_cacerts__hostname_full }}-key.pem exists"
      ansible.builtin.stat:
        path: "{{ deploy_cacerts__cacert_local_key_dir }}/{{ deploy_cacerts__hostname_full }}-key.pem"
      register: cacert_key_result

- name: "{{ __deploy_cacerts__log_prefix_fetch }} Validate cacerts by querying {{ deploy_cacerts__stepca_host_url }}health"
  ignore_errors: true
  ## ref: https://stackoverflow.com/a/66865493
  environment:
    SSL_CERT_FILE: "{{ deploy_cacerts__cacert_local_cert_dir }}/{{ deploy_cacerts__pki_ca_root_cert }}"
  ansible.builtin.uri:
    url: "{{ deploy_cacerts__stepca_host_url }}health"
    method: GET
    status_code: 200
    validate_certs: true
    return_content: false
    ca_path: "{{ deploy_cacerts__cacert_local_cert_dir }}/{{ deploy_cacerts__pki_ca_root_cert }}"
  register: __step_get_result

## ref: https://smallstep.com/docs/step-ca/getting-started#initialize-your-certificate-authority
- name: "{{ __deploy_cacerts__log_prefix_fetch }} Bootstrap step cli configuration"
  changed_when: false
  ansible.builtin.command: |
    step ca bootstrap --force --ca-url {{ deploy_cacerts__stepca_host_url }} \
      --fingerprint {{ __deploy_cacerts__stepca_root_ca_fingerprint }}

#    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Fetch root cert/key from stepca to {{ deploy_cacerts__cacert_local_cert_dir }}"
##      when: not __cacert_root_result.stat.exists
#      ansible.builtin.command: |
#        step ca root {{ deploy_cacerts__cacert_local_cert_dir }}/{{ deploy_cacerts__pki_ca_root_cert }}
#      changed_when: false
#
#    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Copy root cert to {{ __deploy_cacerts__trust_ca_cacert_dir }} for importing"
#      copy_remotely:
#        src: "{{ deploy_cacerts__cacert_local_cert_dir }}/{{ deploy_cacerts__pki_ca_root_cert }}"
#        dest: "{{ __deploy_cacerts__trust_ca_cacert_dir }}/{{ deploy_cacerts__ca_root_cn }}.{{ deploy_cacerts__trust_ca_cert_extension }}"
#
#    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Update CA trust: {{ __deploy_cacerts__trust_ca_update_trust_cmd }}"
#      changed_when: false
#      ansible.builtin.command: "{{ __deploy_cacerts__trust_ca_update_trust_cmd }}"

- name: "{{ __deploy_cacerts__log_prefix_fetch }} Validate root cert"
  when: deploy_cacerts__validate_certs|d(true)|bool
  block:
    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Display ansible_python_interpreter"
      ansible.builtin.debug:
        var: ansible_python_interpreter

    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Validate cacerts by querying {{ deploy_cacerts__stepca_host_url }}health"
      #      ignore_errors: true
      ## ref: https://stackoverflow.com/a/66865493
      environment:
        SSL_CERT_FILE: "{{ deploy_cacerts__cacert_local_cert_dir }}/{{ deploy_cacerts__pki_ca_root_cert }}"
      ansible.builtin.uri:
        url: "{{ deploy_cacerts__stepca_host_url }}health"
        method: GET
        status_code: 200
        validate_certs: true
        return_content: false
        ca_path: "{{ deploy_cacerts__cacert_local_cert_dir }}/{{ deploy_cacerts__pki_ca_root_cert }}"
      register: __step_get_result

- name: "{{ __deploy_cacerts__log_prefix_fetch }} Fetch host cert and key"
  when: deploy_cacerts__deploy_host_certs|d(true)|bool
  block:
    - name: Get firewalld service status
      ansible.builtin.systemd:
        name: firewalld
      register: __firewalld_service_state

    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Temporarily permit traffic on port {{
        __deploy_cacerts__stepca_acme_http_challenge_proxy_port }}/tcp in order to perform stepca host verification"
      when: __firewalld_service_state.status.ActiveState|d('')=='active'
      ansible.posix.firewalld:
        port: "{{ __deploy_cacerts__stepca_acme_http_challenge_proxy_port }}/tcp"
        state: enabled

    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Deploy cert/key to {{ deploy_cacerts__cacert_local_cert_dir }}"
      when: not (cacert_cert_result.stat.exists and cacert_key_result.stat.exists)
      changed_when: false
      ansible.builtin.command: >-
        step ca certificate {{ deploy_cacerts__hostname_full }} \
          {{ deploy_cacerts__cacert_local_cert_dir }}/{{ deploy_cacerts__hostname_full }}.pem \
          {{ deploy_cacerts__cacert_local_key_dir }}/{{ deploy_cacerts__hostname_full }}-key.pem \
          --provisioner {{ deploy_cacerts__ca_provisioner }} \
          --http-listen :{{ __deploy_cacerts__stepca_acme_http_challenge_proxy_port }}

- name: "{{ __deploy_cacerts__log_prefix_fetch }} Create bundle"
  when: deploy_cacerts__create_cert_bundle|d(true)|bool
  block:
    - name: "{{ __deploy_cacerts__log_prefix_fetch }} Create cert bundle from stepca to {{ deploy_cacerts__cacert_local_cert_dir }}"
      when: not (cacert_certbundle_result.stat.exists and cacert_key_result.stat.exists)
      ansible.builtin.command: >-
        step certificate bundle \
          {{ deploy_cacerts__cacert_local_cert_dir }}/{{ deploy_cacerts__hostname_full }}.pem \
          {{ deploy_cacerts__cacert_local_cert_dir }}/{{ deploy_cacerts__pki_ca_root_cert }} \
          {{ deploy_cacerts__cacert_local_cert_dir }}/{{ deploy_cacerts__hostname_full }}.chain.pem
      changed_when: false
