---

- name: read credentials
  register: _creds_json
  changed_when: false
  ansible.builtin.shell:
    cmd: |
      . {{credentials_file}}

      cat <<-EOF
      auth_url: "$OS_AUTH_URL"
      username: "$OS_USERNAME"
      password: "$OS_PASSWORD"
      tenant_name: "$OS_TENANT_NAME"
      project_name: "$OS_PROJECT_NAME"
      user_domain_name: "$OS_USER_DOMAIN_NAME"
      project_domain_name: "$OS_PROJECT_DOMAIN_NAME"
      EOF

- name: set credentials fact
  ansible.builtin.set_fact:
    "{{credentials_fact}}": "{{_creds_json.stdout|from_yaml}}"

