---

docker_stack_postfix_image: "{{ docker_stack_registry_endpoint }}/mail-relay:latest"
#docker_stack_postfix_image: "{{ docker_stack_registry_endpoint }}/postfix:latest"

########## APP CONFIGS #############
smtp_relay_username: "username"
smtp_relay_password: "password"
smtp_relay_host: "smtp.gmail.com"
smtp_relay_port: "587"
smtp_relay_accepted_networks: "192.168.0.0/16 {{ gateway_ipv4_subnet_1_2 }}.0.0/8"
smtp_relay_excludes: "192.168.0.61 192.168.0.7 192.168.0.89"

root_alias_email: "{{ docker_stack_email_from | d('admin@example.com') }}"
#mailman_transport: lists.johnson.int


docker_stack_appspec_config_dirs__postfix:
  - { path: "{{ docker_stack_dir }}/postfix" }

docker_stack_appspec_config_tpls__postfix:
  - { src: 'postfix/rbl_override.j2', dest: "{{ docker_stack_dir }}/postfix/rbl_override"}

docker_stack_firewalld_appspec_ports__postfix:
  - "25/tcp"


docker_stack_appspec__postfix:
  dirs: "{{ docker_stack_appspec_config_dirs__postfix | d([]) }}"
  files: "{{ docker_stack_appspec_config_files__postfix | d([]) }}"
  templates: "{{ docker_stack_appspec_config_tpls__postfix | d([]) }}"
  firewalld_services: "{{ docker_stack_firewalld_appspec_services__postfix | d([]) }}"
  firewalld_ports: "{{ docker_stack_firewalld_appspec_ports__postfix | d([]) }}"
  docker_services: "{{ docker_stack_appspec_services__postfix | d({}) }}"
