---

plex_host: "media.example.int:32400"
plex_host_url: "http://{{ plex_host }}/"
plex_host_ip: "192.168.0.105"
plex_host_port: "32400"
plex_apikey: "apikey"

__docker_stack__appspecs__media_plex_claim: claim-sdfasdfadgadfgdfgadfg

docker_stack__appspec_config_dirs__plex:
  - { path: "{{ docker_stack__dir }}/plex" }

docker_stack__firewalld_appspec_ports__plex:
  - "32400/tcp"
  - "3005/tcp"
  - "8324/tcp"
  - "32469/tcp"
  - "1900/udp"
  - "32410/udp"
  - "32412/udp"
  - "32413/udp"
  - "32414/udp"
  ## webtools for plex
  - "33400/tcp"
  - "33443/tcp"


docker_stack__appspec_services__plex:
  ## Plex Media Server
  plex:
    container_name: plex
    restart: always
    image: plexinc/pms-docker
    volumes:
      - "{{ __docker_stack__appspecs__media_config_dir }}/plex:/config"
      - "/tmp:/transcode"
      - "{{ __docker_stack__appspecs__media_media_path }}:/media"
      - "{{ __docker_stack__appspecs__media_config_dir }}/shared:/shared"
#      - "${USERDIR}/docker/plexms:/config"
#      - "${USERDIR}/Downloads/plex_tmp:/transcode"
#      - "/media/media:/media"
#      - "${USERDIR}/docker/shared:/shared"
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
    environment:
      PLEX_UID: "{{ docker_stack__user_uid }}"
      PLEX_GID: "{{ docker_stack__user_gid }}"
      TZ: "{{ docker_stack__timezone }}"
      HOSTNAME: "Docker Plex"
#      PLEX_CLAIM: "claim-YYYYYYYYY"
#      ADVERTISE_IP: "http://SERVER-IP0:32400/"
      PLEX_CLAIM: "{{ __docker_stack__appspecs__media_plex_claim }}"
      ADVERTISE_IP: "http://plex.{{ docker_stack__internal_domain }}:32400/"
#      ADVERTISE_IP: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:32400/"
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.backend=plexms"
#      - "traefik.frontend.rule=Host:plex.${DOMAINNAME}"
      - "traefik.frontend.rule=Host:plex.{{ docker_stack__internal_domain }}"
      - "traefik.port=32400"
      - "traefik.protocol=http"
      - "traefik.docker.network=traefik_proxy"
      - "traefik.frontend.headers.SSLRedirect=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.browserXSSFilter=true"
      - "traefik.frontend.headers.contentTypeNosniff=true"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.SSLHost=example.com"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"
      - "traefik.frontend.headers.frameDeny=true"


docker_stack__appspec__plex:
  dirs: "{{ docker_stack__appspec_config_dirs__plex | d([]) }}"
  files: "{{ docker_stack__appspec_config_files__plex | d([]) }}"
  templates: "{{ docker_stack__appspec_config_tpls__plex | d([]) }}"
  firewalld_services: "{{ docker_stack__firewalld_appspec_services__plex | d([]) }}"
  firewalld_ports: "{{ docker_stack__firewalld_appspec_ports__plex | d([]) }}"
  docker_services: "{{ docker_stack__appspec_services__plex | d({}) }}"
