---

docker_stack_appspec_networks__bacula:
  ## ref: https://github.com/stefanprodan/swarmprom/blob/master/docker-compose.traefik.yml
  net:
    external: false
    attachable: true

docker_stack_appspec_services__bacula:
  ## ref: https://github.com/fametec/bacula
  bacula-db:
    image: fametec/bacula-catalog:9.6.5
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: bacula
      POSTGRES_USER: bacula
      POSTGRES_DB: bacula
    volumes:
    - pgdata:/var/lib/postgresql/data:rw
    networks:
      - net
    ports:
      - 5432:5432

  bacula-dir:
    image: fametec/bacula-director:9.6.5
    restart: unless-stopped
    volumes:
#        - ./etc/bacula-dir.conf:/opt/bacula/etc/bacula-dir.conf:ro
#        - ./etc/bconsole.conf:/opt/bacula/etc/bconsole.conf:ro
      - "{{ docker_stack_dir }}/bacula/config/bacula-dir.conf:/opt/bacula/etc/bacula-dir.conf:ro"
      - "{{ docker_stack_dir }}/bacula/config/bconsole.conf:/opt/bacula/etc/bconsole.conf.conf:ro"
    depends_on:
      - bacula-db
    networks:
      - net
      - "{{ docker_stack_traefik_proxy_network }}"
    ports:
      - 9101:9101

  bacula-sd:
    image: fametec/bacula-storage:9.6.5
    restart: unless-stopped
    depends_on:
      - bacula-dir
      - bacula-db
    volumes:
#        - ./etc/bacula-sd.conf:/opt/bacula/etc/bacula-sd.conf:ro
      - "{{ docker_stack_dir }}/bacula/config/bacula-sd.conf:/opt/bacula/etc/bacula-sd.conf:ro"
    networks:
      - net
      - "{{ docker_stack_traefik_proxy_network }}"
    ports:
      - 9103:9103

  bacula-fd:
    image: fametec/bacula-client:9.6.5
    restart: unless-stopped
    depends_on:
      - bacula-sd
      - bacula-dir
    volumes:
#        - ./etc/bacula-fd.conf:/opt/bacula/etc/bacula-fd.conf:ro
      - "{{ docker_stack_dir }}/bacula/config/bacula-fd.conf:/opt/bacula/etc/bacula-fd.conf:ro"
    networks:
      - net
      - "{{ docker_stack_traefik_proxy_network }}"
    ports:
      - 9102:9102

docker_stack_appspec__bacula:
  dirs: "{{ docker_stack_appspec_config_dirs__bacula | d([]) }}"
  files: "{{ docker_stack_appspec_config_files__bacula | d([]) }}"
  templates: "{{ docker_stack_appspec_config_tpls__bacula | d([]) }}"
  firewalld_services: "{{ docker_stack_firewalld_appspec_services__bacula | d([]) }}"
  firewalld_ports: "{{ docker_stack_firewalld_appspec_ports__bacula | d([]) }}"
  networks: "{{ docker_stack_appspec_networks__bacula | d({}) }}"
  docker_services: "{{ docker_stack_appspec_services__bacula | d({}) }}"
