---

docker_stack__openresty_backend: "https://openresty.example.int"

docker_stack__appspec_config_dirs__openresty:
  - { path: "{{ docker_stack__dir }}/openresty" }
  - { path: "{{ docker_stack__dir }}/openresty/conf" }
  - { path: "{{ docker_stack__dir }}/openresty/logs" }
  - { path: "{{ docker_stack__dir }}/openresty/vhost" }
  - { path: "{{ docker_stack__dir }}/openresty/site" }
  - { path: "{{ docker_stack__dir }}/openresty/ssl" }

docker_stack__appspec_config_tpls__openresty:
  - { src: "openresty/vhost/dettonville.org.vhost.j2", dest: "{{ docker_stack__dir }}/nginx/vhost/dettonville.org.vhost" }
  - { src: "openresty/ssl/certs/dettonville_org/dettonville_org.cert_chain.crt", dest: "{{ docker_stack__dir }}/nginx/ssl/certs/dettonville_org/dettonville_org.cert_chain.crt" }
  - { src: "openresty/ssl/private/dettonville.org.key", dest: "{{ docker_stack__dir }}/nginx/ssl/private/dettonville.org.key" }
  - { src: "openresty/conf/nginx.conf", dest: "{{ docker_stack__dir }}/nginx/conf/nginx.conf" }
  - { src: "openresty/conf/mime.types.nginx.conf", dest: "{{ docker_stack__dir }}/nginx/conf/mime.types" }
#    - { src: "openresty/conf/blacklist.nginx.conf", dest: "{{ docker_stack__dir }}/nginx/conf/blacklist.conf" }
#    - { src: "openresty/conf/fastcgi.nginx.conf", dest: "{{ docker_stack__dir }}/nginx/conf/fastcgi.conf" }
#    - { src: "openresty/conf/proxy.nginx.conf", dest: "{{ docker_stack__dir }}/nginx/conf/proxy.conf" }
#    - { src: "openresty/conf/fastcgi_microcache_zone.nginx.conf", dest: "{{ docker_stack__dir }}/nginx/conf/fastcgi_microcache_zone.conf" }
#    - { src: "openresty/conf/map_block_http_methods.nginx.conf", dest: "{{ docker_stack__dir }}/nginx/conf/map_block_http_methods.conf" }
#    - { src: "openresty/conf/nginx_status_allowed_hosts.nginx.conf", dest: "{{ docker_stack__dir }}/nginx/conf/nginx_status_allowed_hosts.conf" }
#    - { src: "openresty/conf/perfect-forward-secrecy.nginx.conf", dest: "{{ docker_stack__dir }}/nginx/conf/perfect-forward-secrecy.conf" }
#    - { src: "openresty/conf/proxy_microcache_zone.nginx.conf", dest: "{{ docker_stack__dir }}/nginx/conf/proxy_microcache_zone.conf" }
#    - { src: "openresty/conf/reverse_proxy.nginx.conf", dest: "{{ docker_stack__dir }}/nginx/conf/reverse_proxy.conf" }
#    - { src: "openresty/conf/upstream_phpapache.nginx.conf", dest: "{{ docker_stack__dir }}/nginx/conf/upstream_phpapache.conf" }
#    - { src: "openresty/conf/upstream_phpcgi_tcp.nginx.conf", dest: "{{ docker_stack__dir }}/nginx/conf/upstream_phpcgi_tcp.conf" }


docker_stack__firewalld_appspec_ports__openresty:
  - "11080/tcp"
  - "11443/tcp"


docker_stack__appspec__openresty:
  dirs: "{{ docker_stack__appspec_config_dirs__openresty | d([]) }}"
  files: "{{ docker_stack__appspec_config_files__openresty | d([]) }}"
  templates: "{{ docker_stack__appspec_config_tpls__openresty | d([]) }}"
  firewalld_services: "{{ docker_stack__firewalld_appspec_services__openresty | d([]) }}"
  firewalld_ports: "{{ docker_stack__firewalld_appspec_ports__openresty | d([]) }}"
  docker_services: "{{ docker_stack__appspec_services__openresty | d({}) }}"
