---

- set_fact:
    log_prefix_local: "Docker Stack | Setup Admin Scripts |"

- name: "{{ log_prefix_local }} Ensure script dirs exist"
  file:
    path: "{{ item.path }}"
    state: directory
#    owner: "{{ item.owner | default( docker_stack_user_username ) }}"
#    group: "{{ item.owner | default( docker_stack_user_group ) }}"
    owner: "{{ item.owner | default( 'root' ) }}"
    group: "{{ item.owner | default( 'root' ) }}"
    mode: "{{ item.mode | default(omit) }}"
    recurse: "{{ item.recurse | default( omit ) }}"
  with_items: "{{ docker_stack_script_dirs }}"

## ref: http://www.mydailytutorials.com/ansible-template-module-examples/
- name: "{{ log_prefix_local }} Install docker stack admin/utility scripts"
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    force: "{{ item.force | default('true') }}"
    ## ref: https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html
    mode: "{{ item.mode | default('0770') }}"
#    owner: "{{ item.owner | default( docker_stack_user_username ) }}"
#    group: "{{ item.owner | default( docker_stack_user_group ) }}"
    owner: "{{ item.owner | default( 'root' ) }}"
    group: "{{ item.owner | default( 'root' ) }}"
  with_items: "{{ docker_stack_scripts }}"

## ref: http://www.mydailytutorials.com/ansible-template-module-examples/
- name: "{{ log_prefix_local }} Install admin script configs"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
#    force: "{{ item.force | default('true') }}"
    ## ref: https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters.html
    mode: "{{ item.mode | default('0770') }}"
#    owner: "{{ item.owner | default( docker_stack_user_username ) }}"
#    group: "{{ item.owner | default( docker_stack_user_group ) }}"
    owner: "{{ item.owner | default( 'root' ) }}"
    group: "{{ item.owner | default( 'root' ) }}"
  with_items: "{{ docker_stack_script_config_tpls|d([]) }}"

- name: "Display docker_stack_admin_jobs"
  debug:
    var: docker_stack_admin_jobs

- name: "{{ log_prefix_local }} Create admin cron jobs"
  when: docker_stack_admin_jobs|d([])| count>0
  cron:
    name: "{{ item.name }}"
    special_time: "{{ item.special_time | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    job: "{{ item.job }}"
  with_items: "{{ docker_stack_admin_jobs }}"

