---

#fetch_os_images__osimage_dir: /data/osimages
fetch_os_images__osimage_dir: /data/datacenter/jenkins/osimages

#fetch_os_images__vmware_images_dir: /vmware/iso-repos/linux
#fetch_os_images__vmware_images_dir: /data/vmware/iso-repos/linux
#fetch_os_images__vmware_images_dir: /data/datacenter/vmware/iso-repos/linux
fetch_os_images__vmware_images_dir: /vmware/iso-repos/linux

fetch_os_image__vmware_nfs_iso_locally_mounted: yes

__fetch_images: "{{ fetch_images | d(fetch_os_images__default_os_images) }}"


fetch_os_images__packages: []
#fetch_os_images__packages:
#  ## jigdo-file needed to retrieve debian isos <= version 9 (Stretch)
#  ## ref: https://www.howtoinstall.me/ubuntu/18-04/jigdo-file/
#  - jigdo-file

fetch_os_images__default_os_images:
  - name: centos8
    iso_url: "http://mirror.cc.columbia.edu/pub/linux/centos/8.1.1911/isos/x86_64/CentOS-8.1.1911-x86_64-dvd1.iso"
    iso_file: "CentOS-8.1.1911-x86_64-dvd1.iso"
    iso_checksum: "sha256:3ee3f4ea1538e026fff763e2b284a6f20b259d91d1ad5688f5783a67d279423b"

  - name: centos7
    iso_url: "https://mirror.math.princeton.edu/pub/centos/7.9.2009/isos/x86_64/CentOS-7-x86_64-DVD-2009.iso"
    iso_file: "CentOS-7-x86_64-DVD-2009.iso"
    iso_checksum: "sha256:e33d7b1ea7a9e2f38c8f693215dd85254c3a4fe446f93f563279715b68d07987"

  - name: centos7-2003
    iso_url: "http://mirror.cc.columbia.edu/pub/linux/centos/7.8.2003/isos/x86_64/CentOS-7-x86_64-DVD-2003.iso"
    iso_file: "CentOS-7-x86_64-DVD-2003.iso"
    iso_checksum: "sha256:087a5743dc6fd6706d9b961b8147423ddc029451b938364c760d75440eb7be14"

  - name: centos6
  - name: debian8
  - name: debian9
    iso_url: "https://cdimage.debian.org/cdimage/archive/9.9.0/amd64/jigdo-cd/debian-9.9.0-amd64-netinst.jigdo"
    iso_file: "debian-9.9.0-amd64-netinst.iso"
    iso_checksum: "sha256:d79abe7d607d2ca895f71c2399cfae6153a6f7477356bfd6c10125561654762b"

  - name: debian10
    iso_url: "https://get.debian.org/cdimage/release/current/amd64/iso-cd/debian-10.8.0-amd64-netinst.iso"
    iso_file: "debian-10.8.0-amd64-netinst.iso"
    iso_checksum: "sha256:396553f005ad9f86a51e246b1540c60cef676f9c71b95e22b753faef59f89bee"

  - name: ubuntu16
  - name: ubuntu18
    iso_url: "http://cdimage.ubuntu.com/releases/18.04/release/ubuntu-18.04.5-server-amd64.iso"
    iso_file: "ubuntu-18.04.5-server-amd64.iso"
    iso_checksum: "sha256:8c5fc24894394035402f66f3824beb7234b757dd2b5531379cb310cedfdf0996"
#    iso_file: "ubuntu-18.04.4-server-amd64.iso"
#    iso_checksum: "sha256:e2ecdace33c939527cbc9e8d23576381c493b071107207d2040af72595f8990b"

  - name: ubuntu20
#    iso_url: "http://cdimage.ubuntu.com/ubuntu-legacy-server/releases/20.04/release"
#    iso_file: "ubuntu-20.04.1-legacy-server-amd64.iso"
#    iso_checksum: "sha256:f11bda2f2caed8f420802b59f382c25160b114ccc665dbac9c5046e7fceaced2"
    iso_url: "https://cdimage.ubuntu.com/ubuntu-legacy-server/releases/20.04/release/ubuntu-20.04.1-legacy-server-amd64.iso"
    iso_file: "ubuntu-20.04.1-legacy-server-amd64.iso"
    iso_checksum: "sha256:f11bda2f2caed8f420802b59f382c25160b114ccc665dbac9c5046e7fceaced2"

  - name: ubuntu22
    iso_url: "https://releases.ubuntu.com/22.04/ubuntu-22.04-live-server-amd64.iso"
    iso_file: "ubuntu-22.04-live-server-amd64.iso"
    iso_checksum: "84aeaf7823c8c61baa0ae862d0a06b03409394800000b3235854a6b38eb4856f"

versions: {}
