#- include_tasks: hostname.yml
#- include_tasks: license.yml
#  when: esx_serial is defined
#- include_tasks: dns.yml
- include_tasks: ntp.yml
#- include_tasks: users.yml
#- include_tasks: network.yml
#- include_tasks: storage.yml
#- include_tasks: autostart.yml
#- include_tasks: logging.yml
#- include_tasks: certs.yml
#- include_tasks: software.yml
