---
## ref: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yaml_inventory.html
all:
  hosts:
    admin01.qa.site1.example.dmz:
    trace_var: dmz/site1/admin01.qa.site1.example.dmz
    admin02.qa.site1.example.dmz:
      trace_var: dmz/site1/admin02.qa.site1.example.dmz
    app01.qa.site1.example.dmz:
      trace_var: dmz/site1/app01.qa.site1.example.dmz
    app02.qa.site1.example.dmz:
      trace_var: dmz/site1/app02.qa.site1.example.dmz
    web01.qa.site1.example.dmz:
      trace_var: dmz/site1/web01.qa.site1.example.dmz
    web02.qa.site1.example.dmz:
      trace_var: dmz/site1/web02.qa.site1.example.dmz
  children:
    rhel6:
      vars:
        trace_var: dmz/site1/rhel6
      hosts:
        admin01.qa.site1.example.dmz
    rhel7:
      vars:
        trace_var: dmz/site1/rhel7
      hosts:
        admin02.qa.site1.example.dmz
        app01.qa.site1.example.dmz
        app02.qa.site1.example.dmz
        web01.qa.site1.example.dmz
        web02.qa.site1.example.dmz
    environment_test:
      vars:
        trace_var: dmz/site1/environment_test
      hosts:
        admin01.qa.site1.example.dmz
        admin02.qa.site1.example.dmz
        app01.qa.site1.example.dmz
        app02.qa.site1.example.dmz
        web01.qa.site1.example.dmz
        web02.qa.site1.example.dmz
    location_site1:
      vars:
        trace_var: dmz/site1/location_site1
      hosts:
        admin01.qa.site1.example.dmz
        admin02.qa.site1.example.dmz
        app01.qa.site1.example.dmz
        app02.qa.site1.example.dmz
        web01.qa.site1.example.dmz
        web02.qa.site1.example.dmz
    network_dmz:
      vars:
        trace_var: dmz/site1/dmz
      hosts:
        admin01.qa.site1.example.dmz
        admin02.qa.site1.example.dmz
        app01.qa.site1.example.dmz
        app02.qa.site1.example.dmz
        web01.qa.site1.example.dmz
        web02.qa.site1.example.dmz
    ungrouped: {}
