---

__deploy_pki_certs__trust_cert_extension_default: "crt"

__deploy_pki_certs__ca_cert_bundle_default: /etc/ssl/certs/ca-certificates.crt

__deploy_pki_certs__trust_ca_cert_dir_default: /usr/local/share/ca-certificates
__deploy_pki_certs__trust_ca_update_trust_cmd_default: update-ca-certificates

#__deploy_pki_certs__java_keystore_default: /usr/local/share/java/cacerts
#__deploy_pki_certs__java_keystore_default: /etc/default/cacerts
__deploy_pki_certs__java_keystore_default: /etc/ssl/certs/java/cacerts
