---

__deploy_pki_certs__trust_cert_extension_default: "pem"

## ref: https://stackoverflow.com/questions/37043442/how-to-add-certificate-authority-file-in-centos-7
## ref: https://manuals.gfi.com/en/kerio/connect/content/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html
## ref: https://access.redhat.com/solutions/1549003
__deploy_pki_certs__ca_cert_bundle_default: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem

#__deploy_pki_certs__trust_ca_cert_dir_default: /usr/share/pki/ca-trust-source/anchors
__deploy_pki_certs__trust_ca_cert_dir_default: /etc/pki/ca-trust/source/anchors
__deploy_pki_certs__trust_ca_update_trust_cmd_default: update-ca-trust extract

__deploy_pki_certs__java_keystore_default: /etc/pki/ca-trust/extracted/java/cacerts

# required for validation scripts
__deploy_pki_certs__python_packages:
  - python3-pycurl
  - python3-pyOpenSSL
  - python3-cryptography
