---
- name: reload systemctl
  changed_when: false
  #  ansible.builtin.command: systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: reload ca-certificates
  ansible.builtin.command: "{{ __deploy_pki_certs__trust_ca_update_trust_cmd }}"
  listen: "reload ca certificates"
  changed_when: true
