---

webmin_base_dir: "/usr/share/webmin"

## ref: https://solarianprogrammer.com/2017/06/30/building-python-ubuntu-wsl-debian/
webmin_packages:
  - perl
  - libnet-ssleay-perl
  - openssl
  - libauthen-pam-perl
  - libpam-runtime
  - libio-pty-perl
  - libcgi-pm-perl
  - apt-show-versions
  ## mysql packages
  - libdbd-mysql-perl
  - libdbi-perl
