---
deploy_ca_certs__trust_ca_cacert_dir: "{{ __deploy_ca_certs__trust_ca_cacert_dir_default }}"
deploy_ca_certs__trust_ca_update_trust_cmd: "{{ __deploy_ca_certs__trust_ca_update_trust_cmd_default }}"
