---

## ref: https://blog.linuxserver.io/2020/05/31/deploying-your-own-crypto/
## ref: https://github.com/linuxserver/docker-nano
docker_stack_appspec_services__nano:

  ## Nano is a digital payment protocol designed to be accessible and lightweight,
  ## with a focus on removing inefficiencies present in other cryptocurrencies.
  ## With ultrafast transactions and zero fees on a secure, green and decentralized network,
  ## this makes Nano ideal for everyday transactions.
  nano:
    image: ghcr.io/linuxserver/nano
    container_name: nano
    environment:
      - PUID={{ docker_user_uid }}
      - PGID={{ docker_user_gid }}
      - TZ={{ docker_stack_timezone }}
      ## optional
      - PEER_HOST={{ __docker_stack_appspecs__base_nano_peer_host }}
      - LIVE_GENESIS_PUB={{ __docker_stack_appspecs__base_nano_live_genesis_pub }}
      - LIVE_GENESIS_ACCOUNT={{ __docker_stack_appspecs__base_nano_live_genesis_account }}
      - LIVE_GENESIS_WORK={{ __docker_stack_appspecs__base_nano_live_genesis_work }}
      - LIVE_GENESIS_SIG={{ __docker_stack_appspecs__base_nano_live_genesis_sig }}
      - CLI_OPTIONS={{ __docker_stack_appspecs__base_nano_cli_options }}
      - LMDB_BOOTSTRAP_URL={{ __docker_stack_appspecs__base_nano_lmdb_bootstrap_url }}
      - LMDB_BOOTSTRAP_URL=http://example.com/Nano_64_version_20.7z #optional
    networks:
      - "{{ docker_stack_traefik_proxy_network }}"
    volumes:
      - "{{ __docker_stack_appspecs__base_stack_dir }}/nano:/config"
    ports:
      - 8075:8075
      - 7076:3000
      - 7077:3001
    restart: unless-stopped
#    labels:
#      traefik.enable: true
#      traefik.http.routers.nano.entrypoints: https
#      traefik.http.routers.nano.rule: Host(`nano.{{ docker_stack_internal_domain }}`)
#      traefik.http.routers.nano.service: nano-svc
#      traefik.http.services.nano-svc.loadbalancer.server.port: 7077

