---

bind_listen_ipv4: ['any']
bind_allow_query: ['any']
# bind_zone_primary_server_ip: 192.168.111.222
# bind_zone_primary_server_ip: "{{ hostvars['bind_controller']['ansible_facts']['host'] }}"
# bind_zone_primary_server_ip: "{{ hostvars[inventory_hostname]['ns_controller'] }}"
bind_zone_domains:
  - name: dettonville.int

ns_controller: "admin01.johnson.int"
