---

ca_root_domain: "dettonville.org"

internal_root_domain: "johnson.int"
#internal_root_domain: "dettonville.int"
service_route_internal_root_domain: "dettonville.int"

#ca_signer_common_name: "ca.dettonville.int"
#ca_signer_domain_name: "dettonville.int"
#ca_signerName: "{{ ca_root_cn }}"
ca_country: US
ca_state: "New York"
ca_locality: "NYC"
ca_organization: "Dettonville Internal"
ca_organizationalUnit: "Research & Technology"
ca_email: "admin@{{ ca_domain }}"

#dns_search_domains:
#  - dettonville.int

#ldap_internal_domain: "dettonville.int"
#ldap_internal_base_dn: "dc=dettonville,dc=int"
