---

## ref: https://github.com/lj020326/ansible-role-inspec
inspec_app: inspec
inspec_version: 4.29.3

# inspec_app: inspec
# inspec_version: 4.29.3
# inspec_debian_os: "{{ ansible_facts['distribution'] | lower }}"
# inspec_debian_os_version: "{{ ansible_facts['distribution_major_version'] }}"
# inspec_debian_os_arch: amd64
# inspec_debian_dl_url: "https://packages.chef.io/files/stable/{{ inspec_app }}/{{ inspec_version }}/{{ inspec_debian_os }}/{{ inspec_debian_os_version }}/{{ inspec_app }}_{{ inspec_version }}-1_{{ inspec_debian_os_arch }}.deb"
# inspec_ubuntu_os: "{{ ansible_facts['distribution'] | lower }}"
# inspec_ubuntu_os_version: "{{ ansible_facts['distribution_version']}}"
# inspec_ubuntu_os_arch: amd64
# inspec_ubuntu_dl_url: "https://packages.chef.io/files/stable/{{ inspec_app }}/{{ inspec_version }}/{{ inspec_debian_os }}/{{ inspec_debian_os_version }}/{{ inspec_app }}_{{ inspec_version }}-1_{{ inspec_debian_os_arch }}.deb"
# inspec_el_os: el
# inspec_el_os_arch: x86_64
# inspec_el_os_version: "{{ ansible_facts['distribution_major_version'] }}"
# inspec_el_dl_url: "https://packages.chef.io/files/stable/{{ inspec_app }}/{{ inspec_version }}/{{ inspec_el_os }}/{{ inspec_el_os_version }}/{{ inspec_app }}-{{ inspec_version }}-1.el{{ inspec_el_os_version }}.{{ inspec_el_os_arch }}.rpm"
# inspec_el_disable_gpg_check: false
# inspec_el_rpm_key_url: "https://packages.chef.io/chef.asc"
# inspec_el_rpm_key_fingerprint: "1168 5DB9 2F03 640A 2FFE 7CA8 2940 ABA9 83EF 826A"
# inspec_el_rpm_key_state: present
