---

dc_os_distribution: debian

# bootstrap_user: administrator
# ansible_user: administrator

### CERTS
ca_cert_bundle: "/etc/ssl/certs/ca-certificates.crt"
ca_java_keystore: "/etc/ssl/certs/java/cacerts"

### OS bootstrap
bootstrap_linux_core__init_netplan: true
bootstrap_linux_core__init_network_interfaces: false

trust_ca_cert_extension: "crt"

## ref: https://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate
# trust_ca_cert_dir: /usr/local/share/ca-certificates
trust_ca_cert_dir: /usr/local/share/ca-certificates/extra
trust_ca_update_trust_cmd: update-ca-certificates


### DOCKER
# bootstrap_docker__storage_driver: aufs
