---

#############
## NOTES:
##   common os properties initialized to 'unknown'
##   These will get overridden by child groups when the 'apply_common_groups' role is invoked
##   and applies the host to the correct child/purpose groups
#############
dc_os_family: unknown
dc_os_family_shortname: unknown

dc_os_dist_version: "{{ ansible_facts['distribution_major_version'] | d('') }}"
dc_os_dist_release: "{{ ansible_facts['distribution_release'] | d('') }}"
