---

dc_os_family: windows
dc_os_family_shortname: wnd

ping_test__module: 'win_ping'

## https://docs.ansible.com/ansible/latest/user_guide/windows_winrm.html
## https://docs.ansible.com/ansible/latest/user_guide/windows_winrm.html#inventory-options
ansible_password: "{{ ansible_password__windows }}"
ansible_connection: winrm
ansible_port: 5986
ansible_pipelining: true

ansible_winrm_transport: ntlm
ansible_winrm_scheme: http
ansible_winrm_server_cert_validation: ignore
#ansible_winrm_operation_timeout_sec: 120
ansible_winrm_operation_timeout_sec: 20
ansible_winrm_read_timeout_sec: 150

# May also be passed on the command-line via --user
# ansible_user: Administrator
# ansible_user: ansible

# May also be supplied at runtime with --ask-pass
# ansible_password: SecretPasswordGoesHere

## bootstrap_user: Administrator
# bootstrap_user: ansible
ansible_become: false
ansible_become_method: runas

bootstrap_windows_ansible_username: "{{ ansible_user }}"
# bootstrap_windows_ansible_authorized_public_sshkey: "{{ '~/.ssh/id_rsa.pub' | expanduser }}"
bootstrap_windows_ansible_authorized_public_sshkey: "{{ ansible_ssh_public_key }}"
