---

### DOCKER
#bootstrap_docker__storage_driver: aufs

#bootstrap_linux__network:
#  network:
#    version: 2
#    renderer: networkd
#    ethernets:
#      ens160:
#        dhcp4: yes
#        dhcp6: no
##        ## ref: https://www.oxcrag.net/2019/02/07/creating-a-working-ubuntu-18-04-vmware-template/
##        dhcp-identifier: mac
