---

os_python_interpreter: "/usr/bin/python"
os_pip_bin: "/usr/bin/pip"

#bootstrap_user: administrator
#ansible_user: administrator

### CERTS
ca_cert_bundle: "/etc/ssl/certs/ca-certificates.crt"
ca_java_keystore: "/etc/ssl/certs/java/cacerts"


trust_ca_cert_extension: "crt"

## ref: https://askubuntu.com/questions/73287/how-do-i-install-a-root-certificate
#trust_ca_cacert_dir: /usr/local/share/ca-certificates
trust_ca_cacert_dir: /usr/local/share/ca-certificates/extra
trust_ca_update_trust_cmd: update-ca-certificates


### DOCKER
#docker_storage_driver: aufs
