---

docker_stack__internal_root_domain: "{{ (docker_stack__environment | d('') | length > 0)
  | ternary(docker_stack__environment + '.' + service_route_internal_root_domain,
  service_route_internal_root_domain) }}"
