---

docker_stack__service_groups__stepca:
  - stepca

docker_stack__stepca__password: "{{ vault__stepca_password }}"

# docker_stack__stepca__use_host_cacerts: false
# docker_stack__stepca__use_host_cacerts: true

# docker_stack__stepca__enable_signed: false
docker_stack__stepca__enable_signed: true

#docker_stack__stepca__ca_force_create: true

docker_stack__stepca__root_cacert: "{{ cacert_local_cert_dir }}/ca.{{ docker_stack__internal_domain }}.pem"
docker_stack__stepca__root_cacert_key: "{{ cacert_local_key_dir }}/ca.{{ docker_stack__internal_domain }}-key.pem"

docker_stack__stepca__cacert: "{{ cacert_local_cert_dir }}/{{ docker_stack__internal_domain }}.pem"
docker_stack__stepca__cacert_key: "{{ cacert_local_key_dir }}/{{ docker_stack__internal_domain }}-key.pem"
