---

docker_stack__service_groups__admin:
  - healthchecks
  - registry

# external_domain: "{{ external_root_domain }}"
# docker_stack__external_domain: "{{ external_domain }}"

docker_stack__registry__data_path: "/data/docker_registry_local"

docker_registry_login: true
docker_stack__registry__enable_passthru: false

deploy_pki_certs__ca_reset_local_certs: true
