---

docker_stack__service_groups__keycloak:
  - keycloak

# docker_stack__keycloak__postgres_user: keycloak
# docker_stack__keycloak__postgres_password: "{{ vault__docker_stack__keycloak_postgres_password | d('') }}"
#
#docker_stack__postgres__databases:
#  - "{{ docker_stack__keycloak__postgres_user }},{{ docker_stack__keycloak__postgres_password }}"
