---

docker_stack__service_groups__gitea:
  - gitea

docker_stack__gitea__http_port: 3080
docker_stack__gitea__ssh_port: 2222
docker_stack__gitea__postgres_user: gitea
docker_stack__gitea__postgres_password: "{{ vault__docker_stack__gitea_postgres_password | d('') }}"
