---

docker_stack__service_groups__vault:
  - openbao

docker_stack__openbao__cred_ansible_vault_password: "{{ vault__ansible_vault_password }}"

## the vault host must source the traefik certificate locally to avoid a chicken-egg scenario
## all downstream/consumer nodes can then source signed certificates from the vault pki api
docker_stack__cacerts__fetch_method: "local"

docker_stack__openbao__token_ttl: "{{ ca_certificate_ttl }}"
docker_stack__openbao__token_max_ttl: "{{ ca_certificate_max_ttl }}"

docker_stack__openbao__deploy_policy_name: "{{ ca_deploy_token_name }}"
