---

bootstrap_docker__swarm_leader_host: "{{ groups['docker_swarm_leader_control1'] | first }}"
docker_stack__swarm_leader_host: "{{ groups['docker_swarm_leader_control1'] | first }}"
bootstrap_docker__swarm_managers: "{{ groups['docker_swarm_leader_control1'] + groups['docker_swarm_manager_control1'] }}"

## run 1:10 AM every day
docker_stack__restart_stack_schedule: ["10", "1", "*", "*", "*"]
