---

docker_container_base_dir_nfs: "/data/home/cluster-admin01/docker"

bootstrap_linux_mount__list__admin_prod:
  - name: "{{ docker_container_base_dir }}"
    src: "{{ docker_container_base_dir_nfs }}"
    fstype: none
    options: "bind"
#    options: "rw,auto,bind"

## cat /etc/fstab should contain:
#/data/home/cluster-admin01/docker /home/container-user/docker none bind 0 0
