---

docker_stack__service_groups__admin:
  - healthchecks
  - atlassian

# external_domain: "{{ external_root_domain }}"
# docker_stack__external_domain: "{{ external_domain }}"

docker_registry_login: true
docker_stack__registry__enable_passthru: false
