---

docker_stack__service_groups__stepca:
  - stepca

docker_stack__stepca__password: "{{ vault__stepca_password }}"

# docker_stack__stepca__use_host_cacerts: false
# docker_stack__stepca__use_host_cacerts: true

# docker_stack__stepca__enable_signed: false
docker_stack__stepca__enable_signed: true

#docker_stack__stepca__ca_force_create: true

#docker_stack__stepca__root_cacert: "{{ ca_local_cert_dir }}/ca.{{ docker_stack__internal_domain }}.pem"
#docker_stack__stepca__root_ca_key: "{{ ca_local_key_dir }}/ca.{{ docker_stack__internal_domain }}-key.pem"

docker_stack__stepca__root_cacert: "{{ ca_local_cert_dir }}/{{ docker_stack__internal_domain }}.pem"
docker_stack__stepca__root_ca_key: "{{ ca_local_key_dir }}/{{ docker_stack__internal_domain }}-key.pem"

docker_stack__stepca__cacert: "{{ ca_local_cert_dir }}/{{ docker_stack__internal_domain }}.pem"
docker_stack__stepca__ca_key: "{{ ca_local_key_dir }}/{{ docker_stack__internal_domain }}-key.pem"

deploy_pki_certs__ca_signing_cert_list: []
