---

docker_stack__subdomain: ''

docker_stack__internal_root_domain: "{{ (docker_stack__subdomain | d('', true) | length > 0)
  | ternary(docker_stack__subdomain + '.' + service_route_internal_root_domain,
  service_route_internal_root_domain) }}"
