---
## docker-postfix
## ref: https://emanuelesantanche.com/article/85/configuring-postfix-to-relay-email-through-zoho-mail
docker_stack__postfix__smtp_relay_host: "{{ vault__smtp_relay_host | d('') }}"
docker_stack__postfix__smtp_relay_port: "465"

docker_stack__postfix__smtp_relay_username: "{{ vault__smtp_relay_username | d('') }}"
docker_stack__postfix__smtp_relay_password: "{{ vault__smtp_relay_password | d('') }}"

# docker_stack__postfix__smtp_relay_accepted_networks: "{{ gateway_ipv4_subnet_1_2 }}.0.0/16 172.16.0.0/12 10.0.0.0/8"
docker_stack__postfix__smtp_relay_accepted_networks: "{{ gateway_ipv4_network_cidr }} 172.16.0.0/12"
# docker_stack__postfix__smtp_relay_excludes: "{{ gateway_ipv4_subnet_1_2 }}.0.61 {{ gateway_ipv4_subnet_1_2 }}.0.7 {{ gateway_ipv4_subnet_1_2 }}.0.89"
