---
#os_python_interpreter: "/usr/bin/python"
#os_pip_bin: pip2
#os_python_interpreter: "{{ '/usr/bin/python' if ansible_distribution_major_version == '7' else '/usr/bin/python3' }}"
#os_pip_bin: "{{ 'pip2' if ansible_distribution_major_version == '7' else 'pip3' }}"
#os_pip_bin: "pip3"

ansible_python_interpreter: "{{ os_python3_interpreter }}"
ansible_pip_interpreter: "{{ os_pip3_bin }}"

#bootstrap_username: root
#ansible_user: root

#bootstrap_linux_ansible_sudo_group: wheel
#admin_sudo_group: wheel

### CERTS
#ca_cert_bundle: "/etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt"
ca_cert_bundle: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
#ca_cert_bundle: "/etc/pki/tls/certs/ca-bundle.crt"
#ca_cert_bundle: "/etc/ssl/certs/ca-certificates.crt"
ca_java_keystore: "/etc/pki/ca-trust/extracted/java/cacerts"
#ca_java_keystore: /etc/pki/java/cacerts

trust_ca_cert_extension: "pem"
trust_ca_cacert_dir: /etc/pki/ca-trust/source/anchors
trust_ca_update_trust_cmd: update-ca-trust extract


### DOCKER
#docker_storage_driver: devicemapper
docker_storage_opts: []

#docker_storage_opts:
##  - "dm.thinpooldev=/dev/mapper/docker-thinpool"
#  - "dm.use_deferred_removal=true"
#  - "dm.use_deferred_deletion=true"

