---

postfix_aliases:
  - user: hostmaster
    alias: root
#  - user: root
#    alias: admin@dettonville.org
  - user: root
    alias: admin@dettonville.com

postfix_virtual_aliases:
#  - virtual: root
#    alias: admin@dettonville.org
  - virtual: root
    alias: admin@dettonville.com

postfix_sender_canonical_maps:
#  - sender: root
#    rewrite: admin@dettonville.org
  - sender: root
    rewrite: admin@dettonville.com

postfix_relayhost: "mail.dettonville.int"
postfix_relayhost_port: 25
postfix_sasl_auth_enable: false
postfix_smtpd_use_tls: false
postfix_inet_protocols: ipv4

postfix_disable_vrfy_command: true

#postfix_mailname: "dettonville.org"
#postfix_mydestination: []
postfix_mydestination:
  - "{{ postfix_hostname }}"
  - localdomain
  - localhost
  - localhost.localdomain

postfix_mynetworks:
  - 127.0.0.0/8
  - 172.0.0.0/8
  - "{{ gateway_ip4_subnet_1_2 }}.0.0/{{ ipv4_net_cidr }}"
  - 'localhost'
  - '[::ffff:127.0.0.0]/104'
  - '[::1]/128'

postfix_sasl_user: AKIXXXXXXXXXXXXXXXXX
postfix_sasl_password: ASDFXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

#postfix_smtpd_relay_restrictions: []

postfix_raw_options:
 - |
   debug_peer_list = 10.0.0.15, 10.0.0.135
   #debug_peer_list = 192.168.0.135, 192.168.0.43, 192.168.0.40
   #debug_peer_list = 192.168.0.42
#   debug_peer_list = 192.168.0.15

