---

bootstrap_linux__setup_samba_client: true

samba_domain: EXAMPLE.COM
## mounting /data directly for performance/FACL perms - so no need for samba
samba_mounts: []
# samba_mounts:
#  - name: "/data"
#    src: "//samba.johnson.int/data"
#    fstype: "cifs"
##    options: "vers=3.0,credentials=/root/.smbcredentials,noperm,iocharset=utf8,noserverino,file_mode=0777"
#    options: "credentials=/root/.smbcredentials,noperm,iocharset=utf8,noserverino,file_mode=0777,_netdev"
