---

ansible_user: root
bootstrap_user: root

internal_root_domain: "{{ control_plane_domain_vm }}"

os_python_interpreter: /usr/bin/python

bootstrap_vsphere__vcenter_appliance_name: "{{ inventory_hostname_short }}"
