---

vcenter_ipv4_subnet_1_2: "10.0"
bootstrap_vsphere__vcenter_cluster: "Management"

vcenter_ipv4_host_id: "10"
vcenter_subnet: "{{ vcenter_ipv4_subnet_1_2 }}.10"
vcenter_vmotion_subnet: "{{ gateway_ipv4_subnet_1_2 }}.13"
vcenter_vsan_subnet: "{{ gateway_ipv4_subnet_1_2 }}.14"
vcenter_vmotion_ip: "{{ vcenter_vmotion_subnet }}.{{ vcenter_ipv4_host_id }}"
