---

docker_stack_appspec_services__openresty:
  ## https://www.codenong.com/jse07d79454e61/
  ## https://hub.docker.com/r/openresty/openresty

  openresty:
    container_name: openresty
#      image: 'openresty/openresty'
#      image: 'openresty/openresty:latest-xenial'
    image: 'openresty/openresty:latest-centos'
    restart: "unless-stopped"
    user: "{{ docker_stack_user_uid }}:{{ docker_stack_user_gid }}"
    networks:
      - "{{ docker_stack_traefik_proxy_network }}"
      - net
    ports:
     - "11080:80"
     - "11443:443"
    environment:
      TZ: "{{ docker_stack_timezone }}"
    volumes:
#        - "{{ docker_stack_dir }}/openresty/conf/blacklist.conf:/usr/local/openresty/nginx/conf/blacklist.conf"
#        - "{{ docker_stack_dir }}/openresty/conf/fastcgi.conf:/usr/local/openresty/nginx/conf/fastcgi.conf"
#        - "{{ docker_stack_dir }}/openresty/conf/fastcgi_microcache_zone.conf:/usr/local/openresty/nginx/conf/fastcgi_microcache_zone.conf"
#        - "{{ docker_stack_dir }}/openresty/conf/map_block_http_methods.conf:/usr/local/openresty/nginx/conf/map_block_http_methods.conf"
#        - "{{ docker_stack_dir }}/openresty/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"
#        - "{{ docker_stack_dir }}/openresty/conf/nginx_status_allowed_hosts.conf:/usr/local/openresty/nginx/conf/nginx_status_allowed_hosts.conf"
#        - "{{ docker_stack_dir }}/openresty/conf/perfect-forward-secrecy.conf:/usr/local/openresty/nginx/conf/perfect-forward-secrecy.conf"
#        - "{{ docker_stack_dir }}/openresty/conf/proxy.conf:/usr/local/openresty/nginx/conf/proxy.conf"
#        - "{{ docker_stack_dir }}/openresty/conf/proxy_microcache_zone.conf:/usr/local/openresty/nginx/conf/proxy_microcache_zone.conf"
#        - "{{ docker_stack_dir }}/openresty/conf/reverse_proxy.conf:/usr/local/openresty/nginx/conf/reverse_proxy.conf"
#        - "{{ docker_stack_dir }}/openresty/conf/upstream_phpapache.conf:/usr/local/openresty/nginx/conf/upstream_phpapache.conf"
#        - "{{ docker_stack_dir }}/openresty/conf/upstream_phpcgi_tcp.conf:/usr/local/openresty/nginx/conf/upstream_phpcgi_tcp.conf"
      - "{{ docker_stack_dir }}/openresty/conf:/usr/local/openresty/nginx/conf:ro"
      - "{{ docker_stack_dir }}/openresty/logs:/usr/local/openresty/nginx/logs:rw"
      - "{{ docker_stack_dir }}/openresty/vhost:/etc/nginx/conf.d:ro"
      - "{{ docker_stack_dir }}/openresty/site:/etc/nginx/site:ro"
      - "{{ docker_stack_dir }}/openresty/ssl:/etc/nginx/ssl:ro"



docker_stack_appspec__openresty:
  dirs: "{{ docker_stack_appspec_config_dirs__openresty | d([]) }}"
  files: "{{ docker_stack_appspec_config_files__openresty | d([]) }}"
  templates: "{{ docker_stack_appspec_config_tpls__openresty | d([]) }}"
  firewalld_services: "{{ docker_stack_firewalld_appspec_services__openresty | d([]) }}"
  firewalld_ports: "{{ docker_stack_firewalld_appspec_ports__openresty | d([]) }}"
  docker_services: "{{ docker_stack_appspec_services__openresty | d({}) }}"
