---

__docker_stack__appspecs__traefik_labels_grafana_default:

#docker_stack__appspec_config_tpls__grafana:
#  ## ref: https://github.com/ansible/ansible/issues/22358
#  - { src: "caddy/Caddyfile.j2", dest: "{{ __docker_stack__appspecs__grafana_stack_dir }}/dockerd-exporter/Caddyfile" }


docker_stack__appspec_services__grafana:

  ## Promotheus/Grafana stack per:
  ## ref: https://github.com/stefanprodan/swarmprom/blob/master/docker-compose.traefik.yml
  ## ref: https://github.com/stefanprodan/caddy-dockerd
  dockerd-exporter:
    container_name: "dockerd-exporter"
    image: stefanprodan/caddy
    restart: always
    networks:
      - net
    environment:
      DOCKER_GWBRIDGE_IP: "172.18.0.1"
    configs:
      - source: dockerd_config
        target: /etc/caddy/Caddyfile
#      deploy:
#        mode: global
#        resources:
#          limits:
#            memory: 128M
#          reservations:
#            memory: 64M


docker_stack__appspec__grafana:
  dirs: "{{ docker_stack__appspec_config_dirs__grafana | d([]) }}"
  files: "{{ docker_stack__appspec_config_files__grafana | d([]) }}"
  templates: "{{ docker_stack__appspec_config_tpls__grafana | d([]) }}"
  firewalld_services: "{{ docker_stack__firewalld_appspec_services__grafana | d([]) }}"
  firewalld_ports: "{{ docker_stack__firewalld_appspec_ports__grafana | d([]) }}"
  networks: "{{ docker_stack__appspec_networks__grafana | d({}) }}"
  volumes: "{{ docker_stack__appspec_volumes__grafana | d({}) }}"
  docker_services: "{{ docker_stack__appspec_services__grafana | d({}) }}"
