---
## ref: https://smallstep.com/docs/step-ca/certificate-authority-server-production#the-standalone-step-renewal-daemon
## ref: https://dev.to/kkentzo/deploying-a-service-using-ansible-and-systemd-4n11
## ref: https://stackoverflow.com/questions/35984151/how-to-create-new-system-service-by-ansible-playbook

## ref: https://smallstep.com/docs/step-ca/getting-started#initialize-your-certificate-authority
- name: Stepca-renewal-service | Bootstrap step cli configuration
  changed_when: false
  ansible.builtin.command: |
    step ca bootstrap --force --ca-url {{ deploy_ca_certs__stepca_host_url }} \
      --fingerprint {{ __deploy_ca_certs__stepca_root_ca_fingerprint }}

##- name: Stepca-renewal-service | Create step group
##  ansible.builtin.group:
##    name: step
##    state: present
##
##- name: Stepca-renewal-service | Create Step-ca service account
##  ansible.builtin.user:
##    name: '{{ stepca_svc_user }}'
##    groups: step
##    password: '*'
##    shell: /sbin/nologin
##    append: true
##    state: present
##    create_home: false
##    system: true
#
#- name: "Stepca-renewal-service | Setup systemd service file to server"
#  ansible.builtin.template:
#    src: stepca-renew.service.j2
#    dest: /etc/systemd/system/stepca-renew.service
#    owner: root
#    group: root
#    mode: "0644"
#  notify:
#    - reload systemctl
#
#- name: Stepca-renewal-service | Start stepca renewal service
##  when: deploy_ca_certs__stepca_start_service | d(true) | bool
#  ansible.builtin.service:
#    name: stepca-renew.service
#    state: started
#    enabled: true

## ref: https://techoverflow.net/2020/10/24/create-a-systemd-service-for-your-docker-compose-project-in-10-seconds/
- name: Stepca-renewal-service | Setup stepca-renew.service systemd service
  #  when: deploy_ca_certs__stepca_start_service | d(true) | bool
  ansible.builtin.include_role:
    name: bootstrap_systemd_service
  vars:
    bootstrap_systemd_service__force_update: true
    bootstrap_systemd_service__name: stepca-renew
    bootstrap_systemd_service__envs:
      - PATH=$PATH:/usr/local/bin:/usr/bin:/bin
    bootstrap_systemd_service__Unit_Description: Step TLS Renewer service # noqa: var-naming[pattern]
    bootstrap_systemd_service__Unit_Wants: network.target # noqa: var-naming[pattern]
    bootstrap_systemd_service__Unit_After: network.target # noqa: var-naming[pattern]
    #    bootstrap_systemd_service__Service_Restart: "always" # noqa: var-naming[pattern]
    bootstrap_systemd_service__Service_Restart: on-success # noqa: var-naming[pattern]
    bootstrap_systemd_service__Service_RestartSec: 120 # noqa: var-naming[pattern]
    bootstrap_systemd_service__Service_User: root # noqa: var-naming[pattern]
    bootstrap_systemd_service__Service_ExecStart: >- # noqa: var-naming[pattern]
      step ca renew --daemon {{ deploy_ca_certs__local_cert_dir }}/{{ deploy_ca_certs__hostname_full }}.pem \
        {{ deploy_ca_certs__local_key_dir }}/{{ deploy_ca_certs__hostname_full }}-key.pem
    bootstrap_systemd_service__Install_WantedBy: multi-user.target # noqa: var-naming[pattern]
