---
- name: "{{ __deploy_ca_certs__log_prefix_trust }} ensure trust dir exists for {{ __deploy_ca_certs__trust_ca_cacert_dir }}"
  ansible.builtin.file:
    state: directory
    path: "{{ __deploy_ca_certs__trust_ca_cacert_dir }}"
    mode: "0755"

- name: "{{ __deploy_ca_certs__log_prefix_trust }} Remove all existing old CA certs from {{ __deploy_ca_certs__trust_ca_cacert_dir }}"
  when: deploy_ca_certs__ca_force_distribute_nodes|bool or deploy_ca_certs__ca_force_create|bool
  ansible.builtin.shell: /bin/rm -rf {{ __deploy_ca_certs__trust_ca_cacert_dir }}/*
  changed_when: false

### ref: https://stackoverflow.com/questions/37043442/how-to-add-certificate-authority-file-in-centos-7
### ref: https://www.techrepublic.com/article/how-to-install-ca-certificates-in-ubuntu-server/
### ref: https://gist.github.com/aseigneurin/4902819f17218340d11f
- name: "{{ __deploy_ca_certs__log_prefix_trust }} Copy root cert to {{ __deploy_ca_certs__trust_ca_cacert_dir }} for importing"
  copy_remotely:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: "{{ deploy_ca_certs__local_cert_dir }}/{{ deploy_ca_certs__pki_ca_root_cert }}"
      dest: "{{ __deploy_ca_certs__trust_ca_cacert_dir }}/{{ deploy_ca_certs__ca_root_cn }}.{{ deploy_ca_certs__trust_ca_cert_extension }}"
  register: trust_ca_cacertinstalled

- name: "{{ __deploy_ca_certs__log_prefix_trust }} trust client and intermediate certs"
  when: deploy_ca_certs__deploy_intermediate_certs | d(true) | bool
  block:
    - name: "{{ __deploy_ca_certs__log_prefix_trust }} Copy host cert chain to {{ __deploy_ca_certs__trust_ca_cacert_dir }} for importing"
      copy_remotely:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - src: "{{ deploy_ca_certs__local_cert_dir }}/{{ deploy_ca_certs__hostname_full }}.chain.pem"
          dest: "{{ __deploy_ca_certs__trust_ca_cacert_dir }}/{{ deploy_ca_certs__hostname_full }}.{{ deploy_ca_certs__trust_ca_cert_extension }}"

    - name: "{{ __deploy_ca_certs__log_prefix_trust }} Copy intermediate cert chains to {{ __deploy_ca_certs__trust_ca_cacert_dir }} for importing"
      copy_remotely:
        #        src: "{{ deploy_ca_certs__local_cert_dir }}/{{ item }}.pem"
        src: "{{ deploy_ca_certs__local_cert_dir }}/{{ item }}.chain.pem"
        dest: "{{ __deploy_ca_certs__trust_ca_cacert_dir }}/{{ item }}.{{ deploy_ca_certs__trust_ca_cert_extension }}"
      loop: "{{ __deploy_ca_certs__ca_intermediate_certs | d([]) | list }}"

    - name: "{{ __deploy_ca_certs__log_prefix_trust }} Copy service route cert chains to {{ __deploy_ca_certs__trust_ca_cacert_dir }} for importing"
      copy_remotely:
        #        src: "{{ deploy_ca_certs__local_cert_dir }}/{{ item.route }}.pem"
        src: "{{ deploy_ca_certs__local_cert_dir }}/{{ item.route }}.chain.pem"
        dest: "{{ __deploy_ca_certs__trust_ca_cacert_dir }}/{{ item.route }}.{{ deploy_ca_certs__trust_ca_cert_extension }}"
      loop: "{{ deploy_ca_certs__ca_service_routes_list | d([]) }}"

#- name: "{{ __deploy_ca_certs__log_prefix_trust }} Get list of certs"
#  ansible.builtin.shell: "ls -lR {{ __deploy_ca_certs__trust_ca_cacert_dir }}/"
#  register: ls
#  changed_when: false
#
#- name: "{{ __deploy_ca_certs__log_prefix_trust }} Get list of certs"
#  ansible.builtin.debug:
#    var: ls.stdout_lines
#  when: debug is defined

- name: "{{ __deploy_ca_certs__log_prefix_trust }} Display __deploy_ca_certs__trust_ca_update_trust_cmd"
  ansible.builtin.debug:
    var: __deploy_ca_certs__trust_ca_update_trust_cmd

## need to research for centos how to add multiple CAs - if even possible
## ref: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/using-shared-system-certificates_security-hardening
## ref: https://techjourney.net/update-add-ca-certificates-bundle-in-redhat-centos/
- name: "{{ __deploy_ca_certs__log_prefix_trust }} update CA trust for newly added external certs"
  changed_when: false
  ansible.builtin.command: "{{ __deploy_ca_certs__trust_ca_update_trust_cmd }}"
#  when: trust_ca_cacertinstalled is changed or deploy_ca_certs__ca_force_distribute_nodes|bool

#- name: "{{ __deploy_ca_certs__log_prefix_trust }} convert to pkcs12"
#  ansible.builtin.command: openssl pkcs12 -export \
#    -in {{ ca_path }}/{{ cert_node.domainName }}/{{ cert_node.commonName }}.crt \
#    -inkey {{ ca_path }}/{{ cert_node.domainName}}/{{ cert_node.commonName }}.key \
#    -out {{ ca_path }}/{{ cert_node.domainName }}/{{ cert_node.commonName }}.p12 \
#    -name "{{ cert_node.commonName }}" -passout pass:{{ keystore_password }}

## WORKS on ubuntu20 with openjdk-11
##keytool -importcert -v -storepass changeit   -noprompt   -alias ca-root   -cacerts -file /usr/local/ssl/certs/ca-root.pem

#- name: "{{ __deploy_ca_certs__log_prefix_trust }} Add service cert to keystore"
#  when: deploy_ca_certs__ca_java_keystore_enabled|bool
#  ansible.builtin.command: |
#    keytool -importcert \
#      -storepass {{ deploy_ca_certs__ca_java_keystore_pass }} \
#      -keystore {{ __deploy_ca_certs__ca_java_keystore }} \
#      -noprompt \
#      -alias {{ item.route }} \
#      -file {{ deploy_ca_certs__local_cert_dir }}/{{ item.route }}.pem
#  register: shell_cmd
#  failed_when: shell_cmd.rc > 0 and shell_cmd.stdout | regex_search("Certificate not imported, alias .* already exists") is none
#  loop: "{{ deploy_ca_certs__ca_service_routes_list }}"

#- name: "{{ __deploy_ca_certs__log_prefix_trust }} Add root ca root and host certs to keystore"
#  when: deploy_ca_certs__ca_java_keystore_enabled|bool
#  ansible.builtin.command: |
#    keytool -importcert -v \
#      -storepass {{ deploy_ca_certs__ca_java_keystore_pass }} \
#      -noprompt \
#      -cacerts \
#      -alias {{ item.cn }} \
#      -file {{ item.path }}
#  register: shell_cmd
#  failed_when: shell_cmd.rc > 0 and shell_cmd.stdout | regex_search("Certificate not imported, alias .* already exists") is none
#  loop:
#    - { cn: "{{ deploy_ca_certs__ca_root_cn }}", path: "{{ deploy_ca_certs__local_cert_dir }}/{{ deploy_ca_certs__pki_ca_root_cert }}" }
##    - { cn: "{{ inventory_hostname }}", path: "{{ deploy_ca_certs__local_cert_dir }}/{{ inventory_hostname }}.chain.pem" }

- name: "{{ __deploy_ca_certs__log_prefix_trust }} Update java keystore"
  when: deploy_ca_certs__ca_java_keystore_enabled|bool
  block:
    ## ref: https://superuser.com/questions/881665/keytool-commands-to-replace-existing-ssl-certificate
    ## ref: https://stackoverflow.com/questions/48204014/how-to-delete-already-import-certificate-alias-by-keytool-command
    - name: "{{ __deploy_ca_certs__log_prefix_trust }} Remove old service cert from keystore"
      ansible.builtin.command: |
        keytool -delete -v \
          -storepass {{ deploy_ca_certs__ca_java_keystore_pass }} \
          -noprompt \
          -cacerts \
          -alias {{ item.route }}
      register: keystore_remove_cert
      ignore_errors: true
      #      failed_when: keystore_remove_cert.rc > 0 and keystore_remove_cert.stdout | regex_search("Certificate not imported, alias .* already exists") is none
      loop: "{{ deploy_ca_certs__ca_service_routes_list }}"
      changed_when: false

    - name: Display keystore_remove_cert
      ansible.builtin.debug:
        var: keystore_remove_cert

        verbosity: 1

    - name: "{{ __deploy_ca_certs__log_prefix_trust }} Add current service cert to keystore"
      ansible.builtin.command: |
        keytool -importcert -v \
          -storepass {{ deploy_ca_certs__ca_java_keystore_pass }} \
          -noprompt \
          -cacerts \
          -alias {{ item.route }} \
          -file {{ deploy_ca_certs__local_cert_dir }}/{{ item.route }}.pem
      register: keystore_add_cert
      failed_when:
        - keystore_add_cert.rc > 0
        - keystore_add_cert.stderr | regex_search("Certificate not imported, alias .* already exists") is none
      loop: "{{ deploy_ca_certs__ca_service_routes_list }}"
      changed_when: false
